export const GENERATED_REAL_MOVIES = [
  {
    serial: 'MOV-001',
    title: 'Die Hard',
    synopsis: 'Die Hard es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Die%20Hard%201988%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/ca/Die_Hard_%281988_film%29_poster.jpg',
    releaseYear: 1988,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-002',
    title: 'Mad Max: Fury Road',
    synopsis: 'Mad Max: Fury Road es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Mad%20Max%3A%20Fury%20Road%202015%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg',
    releaseYear: 2015,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-003',
    title: 'John Wick',
    synopsis: 'John Wick es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=John%20Wick%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg',
    releaseYear: 2014,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-004',
    title: 'The Dark Knight',
    synopsis: 'The Dark Knight es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Dark%20Knight%202008%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
    releaseYear: 2008,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-005',
    title: 'Gladiator',
    synopsis: 'Gladiator es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Gladiator%202000%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Gladiators_from_the_Zliten_mosaic_3.JPG',
    releaseYear: 2000,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-006',
    title: 'Terminator 2: Judgment Day',
    synopsis: 'Terminator 2: Judgment Day es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Terminator%202%3A%20Judgment%20Day%201991%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Terminator_2-Judgment_Day.png',
    releaseYear: 1991,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-007',
    title: 'The Matrix',
    synopsis: 'The Matrix es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Matrix%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png',
    releaseYear: 1999,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-008',
    title: 'Kill Bill: Volume 1',
    synopsis: 'Kill Bill: Volume 1 es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Kill%20Bill%3A%20Volume%201%202003%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Kill_Bill_Volume_1.png',
    releaseYear: 2003,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-009',
    title: 'Mission: Impossible – Fallout',
    synopsis: 'Mission: Impossible – Fallout es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Mission%3A%20Impossible%20%E2%80%93%20Fallout%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg',
    releaseYear: 2018,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-010',
    title: 'Top Gun: Maverick',
    synopsis: 'Top Gun: Maverick es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Top%20Gun%3A%20Maverick%202022%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/13/Top_Gun_Maverick_Poster.jpg',
    releaseYear: 2022,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-011',
    title: 'The Raid',
    synopsis: 'The Raid es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Raid%202011%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/9a/The_Raid_2011_poster.jpg',
    releaseYear: 2011,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-012',
    title: 'Casino Royale',
    synopsis: 'Casino Royale es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Casino%20Royale%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/82/Casino_Royale_%282006_film_poster%29.jpg',
    releaseYear: 2006,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-013',
    title: 'Speed',
    synopsis: 'Speed es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Speed%201994%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/45/Speed_movie_poster.jpg',
    releaseYear: 1994,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-014',
    title: 'The Bourne Ultimatum',
    synopsis: 'The Bourne Ultimatum es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Bourne%20Ultimatum%202007%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Ludlum_-_The_Bourne_Ultimatum_Coverart.png',
    releaseYear: 2007,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-015',
    title: 'Skyfall',
    synopsis: 'Skyfall es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Skyfall%202012%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Skyfall_poster.jpg',
    releaseYear: 2012,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-016',
    title: 'Crouching Tiger, Hidden Dragon',
    synopsis: 'Crouching Tiger, Hidden Dragon es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Crouching%20Tiger%2C%20Hidden%20Dragon%202000%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/27/Crouching_Tiger%2C_Hidden_Dragon_%28Chinese_poster%29.png',
    releaseYear: 2000,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-017',
    title: 'Dredd',
    synopsis: 'Dredd es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dredd%202012%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/16/Dredd2012Poster.jpg',
    releaseYear: 2012,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-018',
    title: 'Lethal Weapon',
    synopsis: 'Lethal Weapon es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Lethal%20Weapon%201987%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Lethal_weapon1.jpg',
    releaseYear: 1987,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-019',
    title: 'Heat',
    synopsis: 'Heat es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Heat%201995%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg',
    releaseYear: 1995,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-020',
    title: 'Black Hawk Down',
    synopsis: 'Black Hawk Down es una pelicula reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Black%20Hawk%20Down%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Black_hawk_down_ver1.jpg',
    releaseYear: 2001,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-021',
    title: 'Jurassic Park',
    synopsis: 'Jurassic Park es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Jurassic%20Park%201993%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg',
    releaseYear: 1993,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-022',
    title: 'Raiders of the Lost Ark',
    synopsis: 'Raiders of the Lost Ark es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Raiders%20of%20the%20Lost%20Ark%201981%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a6/Raiders_of_the_Lost_Ark_Theatrical_Poster.jpg',
    releaseYear: 1981,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-023',
    title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    synopsis: 'Pirates of the Caribbean: The Curse of the Black Pearl es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Pirates%20of%20the%20Caribbean%3A%20The%20Curse%20of%20the%20Black%20Pearl%202003%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/89/Pirates_of_the_Caribbean_-_The_Curse_of_the_Black_Pearl.png',
    releaseYear: 2003,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-024',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    synopsis: 'The Lord of the Rings: The Fellowship of the Ring es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Lord%20of%20the%20Rings%3A%20The%20Fellowship%20of%20the%20Ring%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg',
    releaseYear: 2001,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-025',
    title: 'King Kong',
    synopsis: 'King Kong es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=King%20Kong%202005%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Kingkong_bigfinal1.jpg',
    releaseYear: 2005,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-026',
    title: 'Jumanji',
    synopsis: 'Jumanji es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Jumanji%201995%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Jumanji_%28second_logo%29.png',
    releaseYear: 1995,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-027',
    title: 'The Mummy',
    synopsis: 'The Mummy es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Mummy%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/68/The_mummy.jpg',
    releaseYear: 1999,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-028',
    title: 'Life of Pi',
    synopsis: 'Life of Pi es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Life%20of%20Pi%202012%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/45/Life_of_Pi_cover.png',
    releaseYear: 2012,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-029',
    title: 'Avatar',
    synopsis: 'Avatar es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Avatar%202009%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/2/27/Dashavtar_closeup_national_museum_india.JPG',
    releaseYear: 2009,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-030',
    title: 'National Treasure',
    synopsis: 'National Treasure es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=National%20Treasure%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/12/Movie_national_treasure.JPG',
    releaseYear: 2004,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-031',
    title: 'Master and Commander: The Far Side of the World',
    synopsis: 'Master and Commander: The Far Side of the World es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Master%20and%20Commander%3A%20The%20Far%20Side%20of%20the%20World%202003%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/bf/Master_and_Commander-The_Far_Side_of_the_World_poster.png',
    releaseYear: 2003,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-032',
    title: 'The Revenant',
    synopsis: 'The Revenant es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Revenant%202015%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b6/The_Revenant_2015_film_poster.jpg',
    releaseYear: 2015,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-033',
    title: 'Cast Away',
    synopsis: 'Cast Away es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Cast%20Away%202000%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Cast_away_film_poster.jpg',
    releaseYear: 2000,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-034',
    title: 'Romancing the Stone',
    synopsis: 'Romancing the Stone es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Romancing%20the%20Stone%201984%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/84/Romancing_the_stone.jpg',
    releaseYear: 1984,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-035',
    title: 'The Secret Life of Walter Mitty',
    synopsis: 'The Secret Life of Walter Mitty es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Secret%20Life%20of%20Walter%20Mitty%202013%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/f2/The_Secret_Life_of_Walter_Mitty_2013_poster.jpg',
    releaseYear: 2013,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-036',
    title: 'The Goonies',
    synopsis: 'The Goonies es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Goonies%201985%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Goonies.jpg',
    releaseYear: 1985,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-037',
    title: 'Apocalypto',
    synopsis: 'Apocalypto es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Apocalypto%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/62/Apocalypto-poster01.jpg',
    releaseYear: 2006,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-038',
    title: 'The Adventures of Tintin',
    synopsis: 'The Adventures of Tintin es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Adventures%20of%20Tintin%202011%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Tintin-mainCast.png',
    releaseYear: 2011,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-039',
    title: 'Everest',
    synopsis: 'Everest es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Everest%202015%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/28/Everest_poster.jpg',
    releaseYear: 2015,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-040',
    title: 'Kon-Tiki',
    synopsis: 'Kon-Tiki es una pelicula reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Kon-Tiki%202012%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Kon-tiki_2012_Poster.jpg',
    releaseYear: 2012,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-041',
    title: 'Interstellar',
    synopsis: 'Interstellar es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Interstellar%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
    releaseYear: 2014,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-042',
    title: 'Inception',
    synopsis: 'Inception es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Inception%202010%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
    releaseYear: 2010,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-043',
    title: 'Star Wars',
    synopsis: 'Star Wars es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Star%20Wars%201977%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg',
    releaseYear: 1977,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-044',
    title: 'The Empire Strikes Back',
    synopsis: 'The Empire Strikes Back es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Empire%20Strikes%20Back%201980%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/3f/The_Empire_Strikes_Back_%281980_film%29.jpg',
    releaseYear: 1980,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-045',
    title: 'Blade Runner',
    synopsis: 'Blade Runner es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Blade%20Runner%201982%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png',
    releaseYear: 1982,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-046',
    title: '2001: A Space Odyssey',
    synopsis: '2001: A Space Odyssey es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=2001%3A%20A%20Space%20Odyssey%201968%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29.png',
    releaseYear: 1968,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-047',
    title: 'Arrival',
    synopsis: 'Arrival es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Arrival%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/df/Arrival%2C_Movie_Poster.jpg',
    releaseYear: 2016,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-048',
    title: 'Dune',
    synopsis: 'Dune es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dune%202021%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Dune_%282021_film%29.jpg',
    releaseYear: 2021,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-049',
    title: 'Alien',
    synopsis: 'Alien es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Alien%201979%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg',
    releaseYear: 1979,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-050',
    title: 'E.T. the Extra-Terrestrial',
    synopsis: 'E.T. the Extra-Terrestrial es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=E.T.%20the%20Extra-Terrestrial%201982%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg',
    releaseYear: 1982,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-051',
    title: 'Ex Machina',
    synopsis: 'Ex Machina es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ex%20Machina%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Ex-machina-uk-poster.jpg',
    releaseYear: 2014,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-052',
    title: 'Minority Report',
    synopsis: 'Minority Report es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Minority%20Report%202002%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/44/Minority_Report_Poster.jpg',
    releaseYear: 2002,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-053',
    title: 'District 9',
    synopsis: 'District 9 es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=District%209%202009%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d7/District_nine_ver2.jpg',
    releaseYear: 2009,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-054',
    title: 'The Terminator',
    synopsis: 'The Terminator es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Terminator%201984%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6d/The_Terminator.png',
    releaseYear: 1984,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-055',
    title: 'Back to the Future',
    synopsis: 'Back to the Future es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Back%20to%20the%20Future%201985%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg',
    releaseYear: 1985,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-056',
    title: 'The Martian',
    synopsis: 'The Martian es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Martian%202015%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/cd/The_Martian_film_poster.jpg',
    releaseYear: 2015,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-057',
    title: 'Avatar: The Way of Water',
    synopsis: 'Avatar: The Way of Water es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Avatar%3A%20The%20Way%20of%20Water%202022%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/54/Avatar_The_Way_of_Water_poster.jpg',
    releaseYear: 2022,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-058',
    title: 'Close Encounters of the Third Kind',
    synopsis: 'Close Encounters of the Third Kind es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Close%20Encounters%20of%20the%20Third%20Kind%201977%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Close_Encounters_of_the_Third_Kind_%281977%29_theatrical_poster.jpg',
    releaseYear: 1977,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-059',
    title: 'Children of Men',
    synopsis: 'Children of Men es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Children%20of%20Men%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Children_of_men_ver4.jpg',
    releaseYear: 2006,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-060',
    title: 'Edge of Tomorrow',
    synopsis: 'Edge of Tomorrow es una pelicula reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Edge%20of%20Tomorrow%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Edge_of_Tomorrow_Poster.jpg',
    releaseYear: 2014,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-061',
    title: 'The Shawshank Redemption',
    synopsis: 'The Shawshank Redemption es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Shawshank%20Redemption%201994%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
    releaseYear: 1994,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-062',
    title: 'The Godfather',
    synopsis: 'The Godfather es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Godfather%201972%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
    releaseYear: 1972,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-063',
    title: 'Forrest Gump',
    synopsis: 'Forrest Gump es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Forrest%20Gump%201994%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg',
    releaseYear: 1994,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-064',
    title: 'Schindler\'s List',
    synopsis: 'Schindler\'s List es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Schindler\'s%20List%201993%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg',
    releaseYear: 1993,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-065',
    title: 'Fight Club',
    synopsis: 'Fight Club es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Fight%20Club%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
    releaseYear: 1999,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-066',
    title: 'The Green Mile',
    synopsis: 'The Green Mile es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Green%20Mile%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/e2/The_Green_Mile_%28movie_poster%29.jpg',
    releaseYear: 1999,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-067',
    title: 'Good Will Hunting',
    synopsis: 'Good Will Hunting es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Good%20Will%20Hunting%201997%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/52/Good_Will_Hunting.png',
    releaseYear: 1997,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-068',
    title: 'A Beautiful Mind',
    synopsis: 'A Beautiful Mind es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=A%20Beautiful%20Mind%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b8/A_Beautiful_Mind_Poster.jpg',
    releaseYear: 2001,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-069',
    title: 'Parasite',
    synopsis: 'Parasite es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Parasite%202019%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Cymothoa_exigua_parassita_Lithognathus_mormyrus.JPG',
    releaseYear: 2019,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-070',
    title: 'Whiplash',
    synopsis: 'Whiplash es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Whiplash%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg',
    releaseYear: 2014,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-071',
    title: 'There Will Be Blood',
    synopsis: 'There Will Be Blood es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=There%20Will%20Be%20Blood%202007%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg',
    releaseYear: 2007,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-072',
    title: 'Moonlight',
    synopsis: 'Moonlight es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Moonlight%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/84/Moonlight_%282016_film%29.png',
    releaseYear: 2016,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-073',
    title: 'The Pursuit of Happyness',
    synopsis: 'The Pursuit of Happyness es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Pursuit%20of%20Happyness%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/81/Poster-pursuithappyness.jpg',
    releaseYear: 2006,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-074',
    title: 'Oppenheimer',
    synopsis: 'Oppenheimer es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Oppenheimer%202023%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg',
    releaseYear: 2023,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-075',
    title: 'The Departed',
    synopsis: 'The Departed es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Departed%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg',
    releaseYear: 2006,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-076',
    title: 'The Social Network',
    synopsis: 'The Social Network es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Social%20Network%202010%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8c/The_Social_Network_film_poster.png',
    releaseYear: 2010,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-077',
    title: 'No Country for Old Men',
    synopsis: 'No Country for Old Men es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=No%20Country%20for%20Old%20Men%202007%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg',
    releaseYear: 2007,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-078',
    title: 'The Pianist',
    synopsis: 'The Pianist es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Pianist%202002%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg',
    releaseYear: 2002,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-079',
    title: 'Manchester by the Sea',
    synopsis: 'Manchester by the Sea es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Manchester%20by%20the%20Sea%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/de/Manchester_by_the_Sea.jpg',
    releaseYear: 2016,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-080',
    title: '12 Years a Slave',
    synopsis: '12 Years a Slave es una pelicula reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=12%20Years%20a%20Slave%202013%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Solomon_Northup_001.jpg',
    releaseYear: 2013,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-081',
    title: 'The Exorcist',
    synopsis: 'The Exorcist es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Exorcist%201973%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Exorcist_ver2.jpg',
    releaseYear: 1973,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-082',
    title: 'The Shining',
    synopsis: 'The Shining es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Shining%201980%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg',
    releaseYear: 1980,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-083',
    title: 'Get Out',
    synopsis: 'Get Out es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Get%20Out%202017%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png',
    releaseYear: 2017,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-084',
    title: 'A Nightmare on Elm Street',
    synopsis: 'A Nightmare on Elm Street es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=A%20Nightmare%20on%20Elm%20Street%201984%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fa/A_Nightmare_on_Elm_Street_%281984%29_theatrical_poster.jpg',
    releaseYear: 1984,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-085',
    title: 'Halloween',
    synopsis: 'Halloween es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Halloween%201978%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/af/Halloween_%281978%29_theatrical_poster.jpg',
    releaseYear: 1978,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-086',
    title: 'Hereditary',
    synopsis: 'Hereditary es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Hereditary%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Hybridogenesis_in_water_frogs_gametes.svg/250px-Hybridogenesis_in_water_frogs_gametes.svg.png',
    releaseYear: 2018,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-087',
    title: 'The Conjuring',
    synopsis: 'The Conjuring es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Conjuring%202013%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8c/The_Conjuring_poster.jpg',
    releaseYear: 2013,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-088',
    title: 'The Texas Chain Saw Massacre',
    synopsis: 'The Texas Chain Saw Massacre es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Texas%20Chain%20Saw%20Massacre%201974%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a0/The_Texas_Chain_Saw_Massacre_%281974%29_theatrical_poster.jpg',
    releaseYear: 1974,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-089',
    title: 'Scream',
    synopsis: 'Scream es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Scream%201996%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/86/Scream_%281996_film%29_poster.jpg',
    releaseYear: 1996,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-090',
    title: 'Psycho',
    synopsis: 'Psycho es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Psycho%201960%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg',
    releaseYear: 1960,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-091',
    title: 'The Ring',
    synopsis: 'The Ring es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Ring%202002%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/37/Theringpostere.jpg',
    releaseYear: 2002,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-092',
    title: 'Saw',
    synopsis: 'Saw es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Saw%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/56/Saw_official_poster.jpg',
    releaseYear: 2004,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-093',
    title: 'Jaws',
    synopsis: 'Jaws es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Jaws%201975%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/4/40/Jaws_movie_poster.jpg',
    releaseYear: 1975,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-094',
    title: 'A Quiet Place',
    synopsis: 'A Quiet Place es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=A%20Quiet%20Place%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a0/A_Quiet_Place_film_poster.png',
    releaseYear: 2018,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-095',
    title: 'The Babadook',
    synopsis: 'The Babadook es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Babadook%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d7/The-Babadook-Poster.jpg',
    releaseYear: 2014,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-096',
    title: 'The Blair Witch Project',
    synopsis: 'The Blair Witch Project es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Blair%20Witch%20Project%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/26/Blair_Witch_Project.jpg',
    releaseYear: 1999,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-097',
    title: 'Evil Dead II',
    synopsis: 'Evil Dead II es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Evil%20Dead%20II%201987%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6d/Evil_Dead_II_poster.jpg',
    releaseYear: 1987,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-098',
    title: 'It',
    synopsis: 'It es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=It%202017%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg',
    releaseYear: 2017,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-099',
    title: 'The Silence of the Lambs',
    synopsis: 'The Silence of the Lambs es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Silence%20of%20the%20Lambs%201991%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg',
    releaseYear: 1991,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-100',
    title: 'Rosemary\'s Baby',
    synopsis: 'Rosemary\'s Baby es una pelicula reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Rosemary\'s%20Baby%201968%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/ef/Rosemarys_baby_poster.jpg',
    releaseYear: 1968,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-101',
    title: 'Superbad',
    synopsis: 'Superbad es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Superbad%202007%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8b/Superbad_Poster.png',
    releaseYear: 2007,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-102',
    title: 'Groundhog Day',
    synopsis: 'Groundhog Day es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Groundhog%20Day%201993%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Punxsutawney_Phil_Groundhog_Day_2022_Pennsylvania_%2851858203861%29.jpg',
    releaseYear: 1993,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-103',
    title: 'The Hangover',
    synopsis: 'The Hangover es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Hangover%202009%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Hangoverposter09.jpg',
    releaseYear: 2009,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-104',
    title: 'Ghostbusters',
    synopsis: 'Ghostbusters es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ghostbusters%201984%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/2f/Ghostbusters_%281984%29_theatrical_poster.png',
    releaseYear: 1984,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-105',
    title: 'Home Alone',
    synopsis: 'Home Alone es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Home%20Alone%201990%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/76/Home_alone_poster.jpg',
    releaseYear: 1990,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-106',
    title: 'Mean Girls',
    synopsis: 'Mean Girls es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Mean%20Girls%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/ac/Mean_Girls_film_poster.png',
    releaseYear: 2004,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-107',
    title: 'Bridesmaids',
    synopsis: 'Bridesmaids es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Bridesmaids%202011%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/df/BridesmaidsPoster.jpg',
    releaseYear: 2011,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-108',
    title: 'Dumb and Dumber',
    synopsis: 'Dumb and Dumber es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dumb%20and%20Dumber%201994%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/64/Dumbanddumber.jpg',
    releaseYear: 1994,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-109',
    title: 'Ferris Bueller\'s Day Off',
    synopsis: 'Ferris Bueller\'s Day Off es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ferris%20Bueller\'s%20Day%20Off%201986%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Ferris_Bueller%27s_Day_Off.jpg',
    releaseYear: 1986,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-110',
    title: 'Step Brothers',
    synopsis: 'Step Brothers es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Step%20Brothers%202008%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d9/StepbrothersMP08.jpg',
    releaseYear: 2008,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-111',
    title: 'Tropic Thunder',
    synopsis: 'Tropic Thunder es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Tropic%20Thunder%202008%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Tropic_thunder_ver3.jpg',
    releaseYear: 2008,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-112',
    title: 'Anchorman: The Legend of Ron Burgundy',
    synopsis: 'Anchorman: The Legend of Ron Burgundy es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Anchorman%3A%20The%20Legend%20of%20Ron%20Burgundy%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/64/Movie_poster_Anchorman_The_Legend_of_Ron_Burgundy.jpg',
    releaseYear: 2004,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-113',
    title: 'Airplane!',
    synopsis: 'Airplane! es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Airplane!%201980%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/21/Airplane%21_%281980_film%29.jpg',
    releaseYear: 1980,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-114',
    title: 'Shaun of the Dead',
    synopsis: 'Shaun of the Dead es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Shaun%20of%20the%20Dead%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8d/Shaun_of_the_Dead_film_poster.jpg',
    releaseYear: 2004,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-115',
    title: 'Office Space',
    synopsis: 'Office Space es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Office%20Space%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Office_space_poster.jpg',
    releaseYear: 1999,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-116',
    title: 'Borat',
    synopsis: 'Borat es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Borat%202006%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/39/Borat_ver2.jpg',
    releaseYear: 2006,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-117',
    title: 'The Grand Budapest Hotel',
    synopsis: 'The Grand Budapest Hotel es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Grand%20Budapest%20Hotel%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Grand_Budapest_Hotel.png',
    releaseYear: 2014,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-118',
    title: 'Monty Python and the Holy Grail',
    synopsis: 'Monty Python and the Holy Grail es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Monty%20Python%20and%20the%20Holy%20Grail%201975%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/08/Monty-Python-1975-poster.png',
    releaseYear: 1975,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-119',
    title: 'Napoleon Dynamite',
    synopsis: 'Napoleon Dynamite es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Napoleon%20Dynamite%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/87/Napoleon_dynamite_post.jpg',
    releaseYear: 2004,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-120',
    title: 'Clueless',
    synopsis: 'Clueless es una pelicula reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Clueless%201995%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5a/Clueless_film_poster.png',
    releaseYear: 1995,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-121',
    title: 'Titanic',
    synopsis: 'Titanic es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Titanic%201997%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png',
    releaseYear: 1997,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-122',
    title: 'The Notebook',
    synopsis: 'The Notebook es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Notebook%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/86/Posternotebook.jpg',
    releaseYear: 2004,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-123',
    title: 'Pride & Prejudice',
    synopsis: 'Pride & Prejudice es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Pride%20%26%20Prejudice%202005%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/03/Prideandprejudiceposter.jpg',
    releaseYear: 2005,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-124',
    title: 'La La Land',
    synopsis: 'La La Land es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=La%20La%20Land%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png',
    releaseYear: 2016,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-125',
    title: 'Before Sunrise',
    synopsis: 'Before Sunrise es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Before%20Sunrise%201995%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/da/Before_Sunrise_poster.jpg',
    releaseYear: 1995,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-126',
    title: 'Casablanca',
    synopsis: 'Casablanca es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Casablanca%201942%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg',
    releaseYear: 1942,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-127',
    title: 'Roman Holiday',
    synopsis: 'Roman Holiday es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Roman%20Holiday%201953%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Roman_Holiday_%281953_poster%29.jpg',
    releaseYear: 1953,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-128',
    title: 'Eternal Sunshine of the Spotless Mind',
    synopsis: 'Eternal Sunshine of the Spotless Mind es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Eternal%20Sunshine%20of%20the%20Spotless%20Mind%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Eternal_Sunshine_of_the_Spotless_Mind.png',
    releaseYear: 2004,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-129',
    title: 'A Star Is Born',
    synopsis: 'A Star Is Born es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=A%20Star%20Is%20Born%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/39/A_Star_is_Born.png',
    releaseYear: 2018,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-130',
    title: 'Pretty Woman',
    synopsis: 'Pretty Woman es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Pretty%20Woman%201990%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Pretty_woman_movie.jpg',
    releaseYear: 1990,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-131',
    title: 'Ghost',
    synopsis: 'Ghost es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ghost%201990%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/41/Ghost_%281990_movie_poster%29.jpg',
    releaseYear: 1990,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-132',
    title: 'Dirty Dancing',
    synopsis: 'Dirty Dancing es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dirty%20Dancing%201987%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/00/Dirty_Dancing.jpg',
    releaseYear: 1987,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-133',
    title: 'Notting Hill',
    synopsis: 'Notting Hill es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Notting%20Hill%201999%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/0/04/London_110.jpg',
    releaseYear: 1999,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-134',
    title: 'Love Actually',
    synopsis: 'Love Actually es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Love%20Actually%202003%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Love_Actually_movie.jpg',
    releaseYear: 2003,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-135',
    title: 'Brokeback Mountain',
    synopsis: 'Brokeback Mountain es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Brokeback%20Mountain%202005%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a1/Brokeback_mountain.jpg',
    releaseYear: 2005,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-136',
    title: 'Her',
    synopsis: 'Her es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Her%202013%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/44/Her2013Poster.jpg',
    releaseYear: 2013,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-137',
    title: 'The Fault in Our Stars',
    synopsis: 'The Fault in Our Stars es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Fault%20in%20Our%20Stars%202014%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a9/The_Fault_in_Our_Stars.jpg',
    releaseYear: 2014,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-138',
    title: 'Amelie',
    synopsis: 'Amelie es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Amelie%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/53/Amelie_poster.jpg',
    releaseYear: 2001,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-139',
    title: 'Crazy Rich Asians',
    synopsis: 'Crazy Rich Asians es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Crazy%20Rich%20Asians%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Crazy_Rich_Asians_poster.png',
    releaseYear: 2018,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-140',
    title: 'When Harry Met Sally...',
    synopsis: 'When Harry Met Sally... es una pelicula reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=When%20Harry%20Met%20Sally...%201989%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1c/WhenHarryMetSallyPoster.jpg',
    releaseYear: 1989,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-141',
    title: 'Spirited Away',
    synopsis: 'Spirited Away es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Spirited%20Away%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png',
    releaseYear: 2001,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-142',
    title: 'The Lion King',
    synopsis: 'The Lion King es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Lion%20King%201994%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg',
    releaseYear: 1994,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-143',
    title: 'Toy Story',
    synopsis: 'Toy Story es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Toy%20Story%201995%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg',
    releaseYear: 1995,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-144',
    title: 'Finding Nemo',
    synopsis: 'Finding Nemo es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Finding%20Nemo%202003%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg',
    releaseYear: 2003,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-145',
    title: 'Up',
    synopsis: 'Up es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Up%202009%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg',
    releaseYear: 2009,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-146',
    title: 'Coco',
    synopsis: 'Coco es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Coco%202017%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/98/Coco_%282017_film%29_poster.jpg',
    releaseYear: 2017,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-147',
    title: 'WALL-E',
    synopsis: 'WALL-E es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=WALL-E%202008%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4c/WALL-E_poster.jpg',
    releaseYear: 2008,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-148',
    title: 'Shrek',
    synopsis: 'Shrek es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Shrek%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Shrek_%282001_animated_feature_film%29.jpg',
    releaseYear: 2001,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-149',
    title: 'Frozen',
    synopsis: 'Frozen es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Frozen%202013%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg',
    releaseYear: 2013,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-150',
    title: 'Beauty and the Beast',
    synopsis: 'Beauty and the Beast es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Beauty%20and%20the%20Beast%201991%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Beauty_and_the_Beast_%281991_film%29_poster.jpg',
    releaseYear: 1991,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-151',
    title: 'How to Train Your Dragon',
    synopsis: 'How to Train Your Dragon es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=How%20to%20Train%20Your%20Dragon%202010%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/99/How_to_Train_Your_Dragon_logo.png',
    releaseYear: 2010,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-152',
    title: 'Inside Out',
    synopsis: 'Inside Out es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Inside%20Out%202015%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg',
    releaseYear: 2015,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-153',
    title: 'Ratatouille',
    synopsis: 'Ratatouille es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ratatouille%202007%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Ratatouille_home_cooked.jpg',
    releaseYear: 2007,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-154',
    title: 'Spider-Man: Into the Spider-Verse',
    synopsis: 'Spider-Man: Into the Spider-Verse es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Spider-Man%3A%20Into%20the%20Spider-Verse%202018%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Spider-Man_Into_the_Spider-Verse_poster.png',
    releaseYear: 2018,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-155',
    title: 'Princess Mononoke',
    synopsis: 'Princess Mononoke es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Princess%20Mononoke%201997%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Princess_Mononoke_Japanese_poster.png',
    releaseYear: 1997,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-156',
    title: 'The Incredibles',
    synopsis: 'The Incredibles es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Incredibles%202004%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/27/The_Incredibles_%282004_animated_feature_film%29.jpg',
    releaseYear: 2004,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-157',
    title: 'Monsters, Inc.',
    synopsis: 'Monsters, Inc. es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Monsters%2C%20Inc.%202001%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG',
    releaseYear: 2001,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-158',
    title: 'Zootopia',
    synopsis: 'Zootopia es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Zootopia%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/96/Zootopia_%28movie_poster%29.jpg',
    releaseYear: 2016,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-159',
    title: 'Encanto',
    synopsis: 'Encanto es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Encanto%202021%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/83/Encanto_poster.jpg',
    releaseYear: 2021,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Pelicula',
  },
  {
    serial: 'MOV-160',
    title: 'Kubo and the Two Strings',
    synopsis: 'Kubo and the Two Strings es una pelicula reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Kubo%20and%20the%20Two%20Strings%202016%20official%20trailer',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c4/Kubo_and_the_Two_Strings_poster.png',
    releaseYear: 2016,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Pelicula',
  },
] as const;
