export const GENERATED_REAL_SERIES = [
  {
    serial: 'SER-001',
    title: '24',
    synopsis: '24 es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=24%202001%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/24-Logo.svg/960px-24-Logo.svg.png',
    releaseYear: 2001,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-002',
    title: 'Prison Break',
    synopsis: 'Prison Break es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Prison%20Break%202005%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Prison-break-s1-intro.jpg',
    releaseYear: 2005,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-003',
    title: 'Reacher',
    synopsis: 'Reacher es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Reacher%202022%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Reacher_series_title_card.png',
    releaseYear: 2022,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-004',
    title: 'The Punisher',
    synopsis: 'The Punisher es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Punisher%202017%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Punisher_%28TV_series%29_logo.jpg',
    releaseYear: 2017,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-005',
    title: 'Vikings',
    synopsis: 'Vikings es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Vikings%202013%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/99/Vikings_Title.png',
    releaseYear: 2013,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-006',
    title: 'Strike Back',
    synopsis: 'Strike Back es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Strike%20Back%202010%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5d/Strike_Back_title_2011.png',
    releaseYear: 2010,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-007',
    title: 'Banshee',
    synopsis: 'Banshee es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Banshee%202013%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Banshee_%28Home_Box_Office%2C_Inc%29_blood_red_logo.svg/960px-Banshee_%28Home_Box_Office%2C_Inc%29_blood_red_logo.svg.png',
    releaseYear: 2013,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-008',
    title: 'The Last Ship',
    synopsis: 'The Last Ship es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Last%20Ship%202014%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/ec/LastShipSeriesIntertitle.jpg',
    releaseYear: 2014,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-009',
    title: 'S.W.A.T.',
    synopsis: 'S.W.A.T. es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=S.W.A.T.%202017%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/CBP_Office_of_Field_Operations_Training_with_Air_and_Marine_Operations_-_43847567720.jpg',
    releaseYear: 2017,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-010',
    title: 'Arrow',
    synopsis: 'Arrow es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Arrow%202012%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Arrow_Intertitle.png',
    releaseYear: 2012,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-011',
    title: 'Daredevil',
    synopsis: 'Daredevil es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Daredevil%202015%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8a/Daredevil_%28TV_series%29_logo.jpg',
    releaseYear: 2015,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-012',
    title: 'Jack Ryan',
    synopsis: 'Jack Ryan es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Jack%20Ryan%202018%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/12/Jack_Ryan.png',
    releaseYear: 2018,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-013',
    title: 'Warrior',
    synopsis: 'Warrior es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Warrior%202019%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Warrior_%28Tv_series%29.jpg',
    releaseYear: 2019,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-014',
    title: 'Cobra Kai',
    synopsis: 'Cobra Kai es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Cobra%20Kai%202018%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d6/CobraKaiTitleScreen.png',
    releaseYear: 2018,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-015',
    title: 'Peacemaker',
    synopsis: 'Peacemaker es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Peacemaker%202022%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Peacemaker_%28TV_series%29_logo.jpg',
    releaseYear: 2022,
    genreName: 'Accion',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-016',
    title: 'Special Ops: Lioness',
    synopsis: 'Special Ops: Lioness es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Special%20Ops%3A%20Lioness%202023%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/64/Lioness_%282025%29_title_card.jpg',
    releaseYear: 2023,
    genreName: 'Accion',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-017',
    title: 'Titans',
    synopsis: 'Titans es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Titans%202018%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Titans_%282018_TV_series%29_logos.svg/960px-Titans_%282018_TV_series%29_logos.svg.png',
    releaseYear: 2018,
    genreName: 'Accion',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-018',
    title: 'Nikita',
    synopsis: 'Nikita es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Nikita%202010%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Nikita_2010_Intertitle.png',
    releaseYear: 2010,
    genreName: 'Accion',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-019',
    title: 'Spartacus',
    synopsis: 'Spartacus es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Spartacus%202010%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/%CE%A3%CF%80%CE%AC%CF%81%CF%84%CE%B1%CE%BA%CE%BF%CF%82_Spartacus%2CEspartaco_marble_statue_in_Louvre_%22%CE%9C%CE%B1%CE%B9%CE%B4%CE%BF%CE%B9_clan_-Meadow%22_slave_macedon-greek.jpg',
    releaseYear: 2010,
    genreName: 'Accion',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-020',
    title: 'Sons of Anarchy',
    synopsis: 'Sons of Anarchy es una serie reconocida del genero accion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Sons%20of%20Anarchy%202008%20Accion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/7b/SOATitlecard.jpg',
    releaseYear: 2008,
    genreName: 'Accion',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-021',
    title: 'Lost',
    synopsis: 'Lost es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Lost%202004%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lost_main_title.svg/500px-Lost_main_title.svg.png',
    releaseYear: 2004,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-022',
    title: 'The Witcher',
    synopsis: 'The Witcher es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Witcher%202019%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/05/The_Witcher_Logo.png',
    releaseYear: 2019,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-023',
    title: 'His Dark Materials',
    synopsis: 'His Dark Materials es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=His%20Dark%20Materials%202019%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4f/His_Dark_Materials_TV_Title_Card.png',
    releaseYear: 2019,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-024',
    title: 'Merlin',
    synopsis: 'Merlin es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Merlin%202008%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/84/Merlin_-_Screen_Capture.jpg',
    releaseYear: 2008,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-025',
    title: 'Black Sails',
    synopsis: 'Black Sails es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Black%20Sails%202014%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/de/Teaser_Poster_for_Black_Sails.jpg',
    releaseYear: 2014,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-026',
    title: 'The Wheel of Time',
    synopsis: 'The Wheel of Time es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Wheel%20of%20Time%202021%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a1/The_Wheel_of_Time_%28TV_series%29_logo.jpg',
    releaseYear: 2021,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-027',
    title: 'One Piece',
    synopsis: 'One Piece es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=One%20Piece%202023%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/90/One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg',
    releaseYear: 2023,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-028',
    title: 'Outer Banks',
    synopsis: 'Outer Banks es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Outer%20Banks%202020%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/6/65/NCOuterBanks-EO.jpg',
    releaseYear: 2020,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-029',
    title: 'The Adventures of Robin Hood',
    synopsis: 'The Adventures of Robin Hood es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Adventures%20of%20Robin%20Hood%201955%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d2/Robin_Hood_titlecard.jpg',
    releaseYear: 1955,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-030',
    title: 'The Librarians',
    synopsis: 'The Librarians es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Librarians%202014%20Aventura%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMTUyOTY5MDM0MF5BMl5BanBnXkFtZTgwNzU0MzAyNDM@._V1_.jpg',
    releaseYear: 2014,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-031',
    title: 'Marco Polo',
    synopsis: 'Marco Polo es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Marco%20Polo%202014%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4f/Marco_Polo_2014_title_card.jpg',
    releaseYear: 2014,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-032',
    title: 'Primeval',
    synopsis: 'Primeval es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Primeval%202007%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Primeval_Titles_Series_4.JPG',
    releaseYear: 2007,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-033',
    title: 'Atlantis',
    synopsis: 'Atlantis es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Atlantis%202013%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/50/Atlantis_2013_tv_series_titlecard.jpg',
    releaseYear: 2013,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-034',
    title: 'Legend of the Seeker',
    synopsis: 'Legend of the Seeker es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Legend%20of%20the%20Seeker%202008%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Legend_of_the_Seeker_Logo.png',
    releaseYear: 2008,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-035',
    title: 'Terra Nova',
    synopsis: 'Terra Nova es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Terra%20Nova%202011%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Terra_Nova_series_logo.jpg',
    releaseYear: 2011,
    genreName: 'Aventura',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-036',
    title: 'The 100',
    synopsis: 'The 100 es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20100%202014%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Logo_of_the_100.jpg',
    releaseYear: 2014,
    genreName: 'Aventura',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-037',
    title: 'Robin of Sherwood',
    synopsis: 'Robin of Sherwood es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Robin%20of%20Sherwood%201984%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Robinofsherwood.jpg',
    releaseYear: 1984,
    genreName: 'Aventura',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-038',
    title: 'Hercules: The Legendary Journeys',
    synopsis: 'Hercules: The Legendary Journeys es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Hercules%3A%20The%20Legendary%20Journeys%201995%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/04/Hercules_titles.jpg',
    releaseYear: 1995,
    genreName: 'Aventura',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-039',
    title: 'Sinbad',
    synopsis: 'Sinbad es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Sinbad%202012%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Sinbad_Tv_Series_Title.png',
    releaseYear: 2012,
    genreName: 'Aventura',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-040',
    title: 'Renegade Nell',
    synopsis: 'Renegade Nell es una serie reconocida del genero aventura incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Renegade%20Nell%202024%20Aventura%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/27/Renegade_Nell_poster.jpeg',
    releaseYear: 2024,
    genreName: 'Aventura',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-041',
    title: 'Stranger Things',
    synopsis: 'Stranger Things es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Stranger%20Things%202016%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Stranger_Things_logo.png',
    releaseYear: 2016,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-042',
    title: 'Black Mirror',
    synopsis: 'Black Mirror es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Black%20Mirror%202011%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BODcxMWI2NDMtYTc3NC00OTZjLWFmNmUtM2NmY2I1ODkxYzczXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2011,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-043',
    title: 'Doctor Who',
    synopsis: 'Doctor Who es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Doctor%20Who%202005%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d1/Doctor_Who_title_card.png',
    releaseYear: 2005,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-044',
    title: 'The Expanse',
    synopsis: 'The Expanse es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Expanse%202015%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYzUyYmI3MjctY2Q2MC00NmFjLTgwZGUtNWQzZWNlYmVjNzE2XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2015,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-045',
    title: 'Westworld',
    synopsis: 'Westworld es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Westworld%202016%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Westworld_%28TV_series%29_title_card.jpg',
    releaseYear: 2016,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-046',
    title: 'Severance',
    synopsis: 'Severance es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Severance%202022%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BZDI5YzJhODQtMzQyNy00YWNmLWIxMjUtNDBjNjA5YWRjMzExXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2022,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-047',
    title: 'Dark',
    synopsis: 'Dark es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dark%202017%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Creation_of_Light.png',
    releaseYear: 2017,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-048',
    title: 'The X-Files',
    synopsis: 'The X-Files es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20X-Files%201993%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/5e/The_X-Files_original_title_screen.webp',
    releaseYear: 1993,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-049',
    title: 'Fringe',
    synopsis: 'Fringe es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Fringe%202008%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/01/Fringe_intertitle.png',
    releaseYear: 2008,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-050',
    title: 'Battlestar Galactica',
    synopsis: 'Battlestar Galactica es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Battlestar%20Galactica%202004%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/5/57/Battlestar_Galactica_%282004_TV_series%29_title_card.jpg',
    releaseYear: 2004,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-051',
    title: 'Silo',
    synopsis: 'Silo es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Silo%202023%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d0/Silo_Title_Card.png',
    releaseYear: 2023,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-052',
    title: 'Andor',
    synopsis: 'Andor es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Andor%202022%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Andor.svg/960px-Andor.svg.png',
    releaseYear: 2022,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-053',
    title: 'Foundation',
    synopsis: 'Foundation es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Foundation%202021%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMzY5OGJhYzItNGQyOS00NmU3LWFhOWMtNGY1OGVlNTlmYjc0XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2021,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-054',
    title: 'Guillermo del Toro\'s Cabinet of Curiosities',
    synopsis: 'Guillermo del Toro\'s Cabinet of Curiosities es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Guillermo%20del%20Toro\'s%20Cabinet%20of%20Curiosities%202022%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/60/Cabinet_of_curiosities_title_card.png',
    releaseYear: 2022,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-055',
    title: '3 Body Problem',
    synopsis: '3 Body Problem es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=3%20Body%20Problem%202024%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/3_Body_Problem_title_card.png',
    releaseYear: 2024,
    genreName: 'Ciencia Ficcion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-056',
    title: 'Raised by Wolves',
    synopsis: 'Raised by Wolves es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Raised%20by%20Wolves%202020%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Raised_by_Wolves_Title_Card.png',
    releaseYear: 2020,
    genreName: 'Ciencia Ficcion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-057',
    title: 'Altered Carbon',
    synopsis: 'Altered Carbon es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Altered%20Carbon%202018%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Altered_Carbon_title.jpg',
    releaseYear: 2018,
    genreName: 'Ciencia Ficcion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-058',
    title: 'Sense8',
    synopsis: 'Sense8 es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Sense8%202015%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Sense8_Title.png',
    releaseYear: 2015,
    genreName: 'Ciencia Ficcion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-059',
    title: 'Continuum',
    synopsis: 'Continuum es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Continuum%202012%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/f1/Continuum_Title_Card.png',
    releaseYear: 2012,
    genreName: 'Ciencia Ficcion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-060',
    title: 'The Peripheral',
    synopsis: 'The Peripheral es una serie reconocida del genero ciencia ficcion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Peripheral%202022%20Ciencia%20Ficcion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/00/The_Peripheral_title_card.jpg',
    releaseYear: 2022,
    genreName: 'Ciencia Ficcion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-061',
    title: 'Breaking Bad',
    synopsis: 'Breaking Bad es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Breaking%20Bad%202008%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Breaking_Bad_logo.svg/500px-Breaking_Bad_logo.svg.png',
    releaseYear: 2008,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-062',
    title: 'The Sopranos',
    synopsis: 'The Sopranos es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Sopranos%201999%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Sopranos_titlescreen.png',
    releaseYear: 1999,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-063',
    title: 'Mad Men',
    synopsis: 'Mad Men es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Mad%20Men%202007%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/33/Mad-men-title-card.jpg',
    releaseYear: 2007,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-064',
    title: 'The Wire',
    synopsis: 'The Wire es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Wire%202002%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/The_Wire_logo.svg/1280px-The_Wire_logo.svg.png',
    releaseYear: 2002,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-065',
    title: 'Succession',
    synopsis: 'Succession es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Succession%202018%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYTY4YTVkY2QtMjRmOS00YzliLWIxOWQtMTdkOTVkN2UzODNmXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2018,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-066',
    title: 'This Is Us',
    synopsis: 'This Is Us es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=This%20Is%20Us%202016%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNzk4YzY2ZjUtNTQ2YS00MWQ5LTgzZjctZTRlMmZlMzNjNDc3XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2016,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-067',
    title: 'The Crown',
    synopsis: 'The Crown es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Crown%202016%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/1/18/The_Crown_Title_Card.jpg',
    releaseYear: 2016,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-068',
    title: 'Friday Night Lights',
    synopsis: 'Friday Night Lights es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Friday%20Night%20Lights%202006%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/bf/Friday_Night_Lights_title_card.png',
    releaseYear: 2006,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-069',
    title: 'The West Wing',
    synopsis: 'The West Wing es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20West%20Wing%201999%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BY2I2Mzc0YjItN2I3MS00NjNjLWE5OWUtYmQzMjkxZjIwOGY5XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 1999,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-070',
    title: 'The Good Wife',
    synopsis: 'The Good Wife es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Good%20Wife%202009%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMTI2OTk4MDk3OF5BMl5BanBnXkFtZTcwMTY3NTc3Mg@@._V1_.jpg',
    releaseYear: 2009,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-071',
    title: 'Euphoria',
    synopsis: 'Euphoria es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Euphoria%202019%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BZjVlN2M2N2MtOWViZC00MzIxLTlhZWEtMTIwNDIwMzE3ZWJiXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2019,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-072',
    title: 'Better Call Saul',
    synopsis: 'Better Call Saul es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Better%20Call%20Saul%202015%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Better_Call_Saul_logo.svg/500px-Better_Call_Saul_logo.svg.png',
    releaseYear: 2015,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-073',
    title: 'House of Cards',
    synopsis: 'House of Cards es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=House%20of%20Cards%202013%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/3f/House_of_Cards_title_card.png',
    releaseYear: 2013,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-074',
    title: 'Ozark',
    synopsis: 'Ozark es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ozark%202017%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/OzarkOverview.jpg',
    releaseYear: 2017,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-075',
    title: 'Six Feet Under',
    synopsis: 'Six Feet Under es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Six%20Feet%20Under%202001%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/23/Sixfeetunderlogo.jpg',
    releaseYear: 2001,
    genreName: 'Drama',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-076',
    title: 'Downton Abbey',
    synopsis: 'Downton Abbey es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Downton%20Abbey%202010%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c4/Downton_Abbey_Title_Card.jpg',
    releaseYear: 2010,
    genreName: 'Drama',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-077',
    title: 'The Morning Show',
    synopsis: 'The Morning Show es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Morning%20Show%202019%20Drama%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYTY1YjM0Y2QtODFkMy00ZDc4LTg3MWMtMDE4MGY5NzFjYTRhXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2019,
    genreName: 'Drama',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-078',
    title: 'Bloodline',
    synopsis: 'Bloodline es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Bloodline%202015%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/93/Bloodline_TV_Series_Poster.jpg',
    releaseYear: 2015,
    genreName: 'Drama',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-079',
    title: 'The Bear',
    synopsis: 'The Bear es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Bear%202022%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/The_Bear_Title_Card.jpg',
    releaseYear: 2022,
    genreName: 'Drama',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-080',
    title: 'Shogun',
    synopsis: 'Shogun es una serie reconocida del genero drama incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Shogun%202024%20Drama%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Sh%C5%8Dgun_%282024_miniseries%29_poster.jpg',
    releaseYear: 2024,
    genreName: 'Drama',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-081',
    title: 'The Haunting of Hill House',
    synopsis: 'The Haunting of Hill House es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Haunting%20of%20Hill%20House%202018%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/9/92/The_Haunting_of_Hill_House.jpg',
    releaseYear: 2018,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-082',
    title: 'American Horror Story',
    synopsis: 'American Horror Story es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=American%20Horror%20Story%202011%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/American_Horror_Story_%28FX_television_series%29_red_logo.svg/960px-American_Horror_Story_%28FX_television_series%29_red_logo.svg.png',
    releaseYear: 2011,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-083',
    title: 'Penny Dreadful',
    synopsis: 'Penny Dreadful es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Penny%20Dreadful%202014%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Penny_Dreadful_title_card.jpg',
    releaseYear: 2014,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-084',
    title: 'The Walking Dead',
    synopsis: 'The Walking Dead es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Walking%20Dead%202010%20Terror%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYWQwMGRhNGEtZTNhMy00MzVjLWJhMjItYjcwMDljMTkyNTg2XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2010,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-085',
    title: 'From',
    synopsis: 'From es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=From%202022%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fa/From_title_card.jpg',
    releaseYear: 2022,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-086',
    title: 'Marianne',
    synopsis: 'Marianne es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Marianne%202019%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/40/Marianne_series.jpg',
    releaseYear: 2019,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-087',
    title: 'The Fall of the House of Usher',
    synopsis: 'The Fall of the House of Usher es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Fall%20of%20the%20House%20of%20Usher%202023%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Netflix_Fall_of_House_of_Usher_series.png',
    releaseYear: 2023,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-088',
    title: 'The Strain',
    synopsis: 'The Strain es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Strain%202014%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/e/e0/The_Strain_2014_Intertitle.jpg',
    releaseYear: 2014,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-089',
    title: 'Channel Zero',
    synopsis: 'Channel Zero es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Channel%20Zero%202016%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/7d/Channel_Zero_TV_series_logo.jpg',
    releaseYear: 2016,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-090',
    title: 'Bates Motel',
    synopsis: 'Bates Motel es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Bates%20Motel%202013%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/2/23/BatesMotelTitle.jpg',
    releaseYear: 2013,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-091',
    title: 'Castle Rock',
    synopsis: 'Castle Rock es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Castle%20Rock%202018%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/8a/CastleRock.png',
    releaseYear: 2018,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-092',
    title: 'Ash vs Evil Dead',
    synopsis: 'Ash vs Evil Dead es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ash%20vs%20Evil%20Dead%202015%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Ash_vs_Evil_Dead.svg/960px-Ash_vs_Evil_Dead.svg.png',
    releaseYear: 2015,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-093',
    title: 'Midnight Mass',
    synopsis: 'Midnight Mass es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Midnight%20Mass%202021%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/da/Midnight_Mass_Poster.jpg',
    releaseYear: 2021,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-094',
    title: 'The Terror',
    synopsis: 'The Terror es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Terror%202018%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/ca/The-Terror-TV.png',
    releaseYear: 2018,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-095',
    title: 'The Outsider',
    synopsis: 'The Outsider es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Outsider%202020%20Terror%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BOGY0YjJmOWItOGI2MS00N2VmLTlmNjYtMDM3YjY1MzkyM2E1XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2020,
    genreName: 'Terror',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-096',
    title: 'Archive 81',
    synopsis: 'Archive 81 es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Archive%2081%202022%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Archive_81_poster.jpg',
    releaseYear: 2022,
    genreName: 'Terror',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-097',
    title: 'Chucky',
    synopsis: 'Chucky es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Chucky%202021%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Chucky_%282021_television_series%29.png',
    releaseYear: 2021,
    genreName: 'Terror',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-098',
    title: 'Slasher',
    synopsis: 'Slasher es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Slasher%202016%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/Slasher_TV_logo.png',
    releaseYear: 2016,
    genreName: 'Terror',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-099',
    title: 'Them',
    synopsis: 'Them es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Them%202021%20Terror%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Them_2021_Television_Series_poster.png',
    releaseYear: 2021,
    genreName: 'Terror',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-100',
    title: 'The Last of Us',
    synopsis: 'The Last of Us es una serie reconocida del genero terror incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Last%20of%20Us%202023%20Terror%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYWI3ODJlMzktY2U5NC00ZjdlLWE1MGItNWQxZDk3NWNjN2RhXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2023,
    genreName: 'Terror',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-101',
    title: 'Friends',
    synopsis: 'Friends es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Friends%201994%20Comedia%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BOTU2YmM5ZjctOGVlMC00YTczLTljM2MtYjhlNGI5YWMyZjFkXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 1994,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-102',
    title: 'The Office',
    synopsis: 'The Office es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Office%202005%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/81/Two_Offices.jpg',
    releaseYear: 2005,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-103',
    title: 'Parks and Recreation',
    synopsis: 'Parks and Recreation es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Parks%20and%20Recreation%202009%20Comedia%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNDlhMzAwNTAtNTk2NS00MTdkLWE3ZWYtMDU0MTFiYmU2ZTc0XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2009,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-104',
    title: 'Brooklyn Nine-Nine',
    synopsis: 'Brooklyn Nine-Nine es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Brooklyn%20Nine-Nine%202013%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Brooklyn_Nine-Nine_Logo.png',
    releaseYear: 2013,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-105',
    title: 'Seinfeld',
    synopsis: 'Seinfeld es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Seinfeld%201989%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Seinfeld_logo.svg/250px-Seinfeld_logo.svg.png',
    releaseYear: 1989,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-106',
    title: 'Modern Family',
    synopsis: 'Modern Family es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Modern%20Family%202009%20Comedia%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYzFlOWFjNzQtODViNC00NzgzLThhZmItZTc1N2VlZDgwODUwXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2009,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-107',
    title: 'Ted Lasso',
    synopsis: 'Ted Lasso es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Ted%20Lasso%202020%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/7/73/Tedlassotitlecard.jpg',
    releaseYear: 2020,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-108',
    title: 'Arrested Development',
    synopsis: 'Arrested Development es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Arrested%20Development%202003%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Arrested_Development.svg/500px-Arrested_Development.svg.png',
    releaseYear: 2003,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-109',
    title: 'The Good Place',
    synopsis: 'The Good Place es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Good%20Place%202016%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/The_Good_Place_title_card.svg/1920px-The_Good_Place_title_card.svg.png',
    releaseYear: 2016,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-110',
    title: '30 Rock',
    synopsis: '30 Rock es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=30%20Rock%202006%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/30Rock_logo.svg/960px-30Rock_logo.svg.png',
    releaseYear: 2006,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-111',
    title: 'How I Met Your Mother',
    synopsis: 'How I Met Your Mother es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=How%20I%20Met%20Your%20Mother%202005%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/HowIMetYourMother.svg/960px-HowIMetYourMother.svg.png',
    releaseYear: 2005,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-112',
    title: 'Community',
    synopsis: 'Community es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Community%202009%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/3/39/A_community_townhall_at_Makoko_community.jpg',
    releaseYear: 2009,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-113',
    title: 'Curb Your Enthusiasm',
    synopsis: 'Curb Your Enthusiasm es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Curb%20Your%20Enthusiasm%202000%20Comedia%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BZmFiZDY2ZDItZDliOC00Y2JhLTliMWYtODkzMTA0YmIwZDA3XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2000,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-114',
    title: 'Schitt\'s Creek',
    synopsis: 'Schitt\'s Creek es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Schitt\'s%20Creek%202015%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Schitt%27s_Creek_logo.svg/1920px-Schitt%27s_Creek_logo.svg.png',
    releaseYear: 2015,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-115',
    title: 'Only Murders in the Building',
    synopsis: 'Only Murders in the Building es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Only%20Murders%20in%20the%20Building%202021%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/be/Only_Murders_logo.jpeg',
    releaseYear: 2021,
    genreName: 'Comedia',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-116',
    title: 'Abbott Elementary',
    synopsis: 'Abbott Elementary es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Abbott%20Elementary%202021%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/AbbottElementary.png',
    releaseYear: 2021,
    genreName: 'Comedia',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-117',
    title: 'Silicon Valley',
    synopsis: 'Silicon Valley es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Silicon%20Valley%202014%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/33/Silicon_valley_title.png',
    releaseYear: 2014,
    genreName: 'Comedia',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-118',
    title: 'The Marvelous Mrs. Maisel',
    synopsis: 'The Marvelous Mrs. Maisel es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Marvelous%20Mrs.%20Maisel%202017%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/The_Marvelous_Mrs._Maisel.svg/250px-The_Marvelous_Mrs._Maisel.svg.png',
    releaseYear: 2017,
    genreName: 'Comedia',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-119',
    title: 'What We Do in the Shadows',
    synopsis: 'What We Do in the Shadows es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=What%20We%20Do%20in%20the%20Shadows%202019%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/31/What_We_Do_in_the_Shadows_Title_Card.jpg',
    releaseYear: 2019,
    genreName: 'Comedia',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-120',
    title: 'Master of None',
    synopsis: 'Master of None es una serie reconocida del genero comedia incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Master%20of%20None%202015%20Comedia%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Master_of_None_Logo.svg/960px-Master_of_None_Logo.svg.png',
    releaseYear: 2015,
    genreName: 'Comedia',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-121',
    title: 'Bridgerton',
    synopsis: 'Bridgerton es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Bridgerton%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/3d/Bridgerton_Title_Card.png',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-122',
    title: 'Normal People',
    synopsis: 'Normal People es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Normal%20People%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Normal_People_%28Rooney_novel%29.png',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-123',
    title: 'Outlander',
    synopsis: 'Outlander es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Outlander%202014%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/31/Outlander_title_card.jpg',
    releaseYear: 2014,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-124',
    title: 'Jane the Virgin',
    synopsis: 'Jane the Virgin es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Jane%20the%20Virgin%202014%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Jane_the_Virgin.png',
    releaseYear: 2014,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-125',
    title: 'Heartstopper',
    synopsis: 'Heartstopper es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Heartstopper%202022%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/89/Heartstopper_title-card.png',
    releaseYear: 2022,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-126',
    title: 'The Summer I Turned Pretty',
    synopsis: 'The Summer I Turned Pretty es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Summer%20I%20Turned%20Pretty%202022%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d1/The_Summer_I_Turned_Pretty_%28TV_series%29_Title_Card.png',
    releaseYear: 2022,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-127',
    title: 'Emily in Paris',
    synopsis: 'Emily in Paris es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Emily%20in%20Paris%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Emily_in_Paris_logo.svg/500px-Emily_in_Paris_logo.svg.png',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-128',
    title: 'Crash Landing on You',
    synopsis: 'Crash Landing on You es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Crash%20Landing%20on%20You%202019%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/6/64/Crash_Landing_on_You_main_poster.jpg',
    releaseYear: 2019,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-129',
    title: 'Dash & Lily',
    synopsis: 'Dash & Lily es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Dash%20%26%20Lily%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMzg3ZTcyMWUtODY4Yy00MzgwLTkyYzQtNzBkNzMyZTBjY2VlXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-130',
    title: 'Virgin River',
    synopsis: 'Virgin River es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Virgin%20River%202019%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/fa/Virgin_River_%28TV_series%29_Title_Card.jpg',
    releaseYear: 2019,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-131',
    title: 'Love',
    synopsis: 'Love es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Love%202016%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Love_TV_Logo.png',
    releaseYear: 2016,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-132',
    title: 'Younger',
    synopsis: 'Younger es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Younger%202015%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/f/f7/Younger_TV_Land.png',
    releaseYear: 2015,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-133',
    title: 'Poldark',
    synopsis: 'Poldark es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Poldark%202015%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/3c/Poldark_2015_TV_series_titlecard.jpg',
    releaseYear: 2015,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-134',
    title: 'Sweet Magnolias',
    synopsis: 'Sweet Magnolias es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Sweet%20Magnolias%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/b/bb/Sweet_Magnolias_Title_Card.png',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-135',
    title: 'A Discovery of Witches',
    synopsis: 'A Discovery of Witches es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=A%20Discovery%20of%20Witches%202018%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/0/02/A_Discovery_of_Witches_%28TV_series%29.png',
    releaseYear: 2018,
    genreName: 'Romance',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-136',
    title: 'Maxton Hall',
    synopsis: 'Maxton Hall es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Maxton%20Hall%202024%20Romance%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYjZjYThlNWYtNzI3NS00MWE2LWI5NDEtNDAzMTZmYTdjNzc3XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2024,
    genreName: 'Romance',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-137',
    title: 'Sex Education',
    synopsis: 'Sex Education es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Sex%20Education%202019%20Romance%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BOTE0MjQ1NDU3OV5BMl5BanBnXkFtZTgwNTI4MTgwNzM@._V1_.jpg',
    releaseYear: 2019,
    genreName: 'Romance',
    directorName: 'James Cameron',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-138',
    title: 'One Day',
    synopsis: 'One Day es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=One%20Day%202024%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/85/This_is_a_poster_for_the_One_Day_%28TV_Series%29.jpg',
    releaseYear: 2024,
    genreName: 'Romance',
    directorName: 'Ridley Scott',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-139',
    title: 'Starstruck',
    synopsis: 'Starstruck es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Starstruck%202021%20Romance%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNDRmMzM0ZDctNjQwOS00NjZlLTk1MTYtNzVmYWI0NWUzMzI5XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2021,
    genreName: 'Romance',
    directorName: 'Christopher Nolan',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-140',
    title: 'Love Life',
    synopsis: 'Love Life es una serie reconocida del genero romance incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Love%20Life%202020%20Romance%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Love_Life_%28Logo%29.png',
    releaseYear: 2020,
    genreName: 'Romance',
    directorName: 'Steven Spielberg',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-141',
    title: 'Avatar: The Last Airbender',
    synopsis: 'Avatar: The Last Airbender es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Avatar%3A%20The%20Last%20Airbender%202005%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Avatar_The_Last_Airbender_logo.svg/330px-Avatar_The_Last_Airbender_logo.svg.png',
    releaseYear: 2005,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-142',
    title: 'Arcane',
    synopsis: 'Arcane es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Arcane%202021%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYjA2NzhlMDItNWRmZC00MzRjLWE3ZjAtZjBlZDAwOWY2ODdjXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2021,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-143',
    title: 'Batman: The Animated Series',
    synopsis: 'Batman: The Animated Series es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Batman%3A%20The%20Animated%20Series%201992%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BYjgwZWUzMzUtYTFkNi00MzM0LWFkMWUtMDViMjMxNGIxNDUxXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 1992,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-144',
    title: 'BoJack Horseman',
    synopsis: 'BoJack Horseman es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=BoJack%20Horseman%202014%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/BoJack_Horseman_Logo.svg/960px-BoJack_Horseman_Logo.svg.png',
    releaseYear: 2014,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-145',
    title: 'Bluey',
    synopsis: 'Bluey es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Bluey%202018%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/4/48/Bluey_%282018_TV_series%29_title_card.jpg',
    releaseYear: 2018,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-146',
    title: 'Rick and Morty',
    synopsis: 'Rick and Morty es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Rick%20and%20Morty%202013%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BZGQyZjk2MzMtMTcyNC00NGU3LTlmNjItNDExMWM4ZDFhYmQ2XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2013,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-147',
    title: 'Samurai Jack',
    synopsis: 'Samurai Jack es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Samurai%20Jack%202001%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BNjU4ZmVhZGMtNTU4Yy00YmZhLTlmOGQtNGMwMTcwNTEyZjQ0XkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2001,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-148',
    title: 'Adventure Time',
    synopsis: 'Adventure Time es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Adventure%20Time%202010%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/3/37/Adventure_Time_-_Title_card.png',
    releaseYear: 2010,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-149',
    title: 'Gravity Falls',
    synopsis: 'Gravity Falls es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Gravity%20Falls%202012%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Gravity_Falls_logo.png',
    releaseYear: 2012,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-150',
    title: 'SpongeBob SquarePants',
    synopsis: 'SpongeBob SquarePants es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=SpongeBob%20SquarePants%201999%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/22/SpongeBob_SquarePants_logo_by_Nickelodeon.svg/500px-SpongeBob_SquarePants_logo_by_Nickelodeon.svg.png',
    releaseYear: 1999,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-151',
    title: 'The Simpsons',
    synopsis: 'The Simpsons es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Simpsons%201989%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/The_Simpsons_yellow_logo.svg/1920px-The_Simpsons_yellow_logo.svg.png',
    releaseYear: 1989,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-152',
    title: 'Futurama',
    synopsis: 'Futurama es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Futurama%201999%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Futurama_1999_logo.svg/1280px-Futurama_1999_logo.svg.png',
    releaseYear: 1999,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
  {
    serial: 'SER-153',
    title: 'Attack on Titan',
    synopsis: 'Attack on Titan es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Attack%20on%20Titan%202013%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg',
    releaseYear: 2013,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'Walt Disney Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-154',
    title: 'Fullmetal Alchemist: Brotherhood',
    synopsis: 'Fullmetal Alchemist: Brotherhood es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Fullmetal%20Alchemist%3A%20Brotherhood%202009%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMzNiODA5NjYtYWExZS00OTc4LTg3N2ItYWYwYTUyYmM5MWViXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2009,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Warner Bros. Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-155',
    title: 'Invincible',
    synopsis: 'Invincible es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Invincible%202021%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BZjE4ZDU4ZjMtZjliYS00M2ZmLThkNTItN2U3MmJjOGU0NmIxXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2021,
    genreName: 'Animacion',
    directorName: 'James Cameron',
    producerName: 'Paramount Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-156',
    title: 'The Legend of Korra',
    synopsis: 'The Legend of Korra es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Legend%20of%20Korra%202012%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/8/85/Legend_of_Korra_logo.png',
    releaseYear: 2012,
    genreName: 'Animacion',
    directorName: 'Ridley Scott',
    producerName: 'Metro-Goldwyn-Mayer',
    typeName: 'Serie',
  },
  {
    serial: 'SER-157',
    title: 'Cowboy Bebop',
    synopsis: 'Cowboy Bebop es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Cowboy%20Bebop%201998%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Cowboy_Bebop_key_visual.jpg',
    releaseYear: 1998,
    genreName: 'Animacion',
    directorName: 'Christopher Nolan',
    producerName: 'Universal Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-158',
    title: 'Love, Death & Robots',
    synopsis: 'Love, Death & Robots es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Love%2C%20Death%20%26%20Robots%202019%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Love%2C_Death_%26_Robots_Logo.png',
    releaseYear: 2019,
    genreName: 'Animacion',
    directorName: 'Steven Spielberg',
    producerName: '20th Century Studios',
    typeName: 'Serie',
  },
  {
    serial: 'SER-159',
    title: 'Primal',
    synopsis: 'Primal es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=Primal%202019%20Animacion%20official%20trailer%20series',
    coverImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Primal_logo.svg/250px-Primal_logo.svg.png',
    releaseYear: 2019,
    genreName: 'Animacion',
    directorName: 'Martin Scorsese',
    producerName: 'DreamWorks Pictures',
    typeName: 'Serie',
  },
  {
    serial: 'SER-160',
    title: 'The Dragon Prince',
    synopsis: 'The Dragon Prince es una serie reconocida del genero animacion incluida en el catalogo inicial con una portada real y una referencia publica de trailer.',
    url: 'https://www.youtube.com/results?search_query=The%20Dragon%20Prince%202018%20Animacion%20official%20trailer%20series',
    coverImage: 'https://m.media-amazon.com/images/M/MV5BMDg2YjI2YjYtYjY2Ny00ODg2LWIxNWQtODM3NjE1MzNkNjExXkEyXkFqcGc@._V1_.jpg',
    releaseYear: 2018,
    genreName: 'Animacion',
    directorName: 'Quentin Tarantino',
    producerName: 'Miramax Films',
    typeName: 'Serie',
  },
] as const;
