// src/database/seeds/store.seed.ts

/**
 * @fileoverview Seed de tiendas Taco Bell (República Dominicana + Costa Rica)
 * @module database/seeds
 *
 * República Dominicana — 20 tiendas:
 * - Santo Domingo (10), Santiago (2), Punta Cana/Bávaro (2),
 *   La Romana (1), Higüey (1), San Cristóbal (1),
 *   San Francisco de Macorís (1), La Vega (1), Puerto Plata (1)
 *
 * Costa Rica — 49 tiendas:
 * - San José provincia (22), Alajuela (8), Cartago (7),
 *   Heredia (5), Guanacaste (2), Puntarenas (2),
 *   Limón (2), Pérez Zeledón (1)
 */

import { DataSource } from 'typeorm';
import { StoreEntity } from '@modules/store/entities';
import { CompanyEntity } from '@modules/company/entities';
import { GeoCityEntity } from '@modules/geography/entities';

/**
 * Mapa de ciudad del store → nombre de ciudad en el catálogo geográfico
 * (usa nombres normalizados o aliases del seed de geografía)
 */
const CITY_LOOKUP: Record<string, string[]> = {
  // ── República Dominicana ──
  'Santo Domingo': ['Santo Domingo'],
  Santiago: ['Santiago', 'Santiago de los Caballeros'],
  'Punta Cana': ['Punta Cana', 'Higuey', 'Salvaleon de Higuey'],
  'La Romana': ['La Romana'],
  Higüey: ['Higuey', 'Salvaleon de Higuey'],
  'San Cristóbal': ['San Cristobal'],
  'San Francisco de Macorís': ['San Francisco de Macoris', 'SFM'],
  'La Vega': ['La Vega', 'Concepcion de La Vega'],
  'Puerto Plata': ['Puerto Plata', 'San Felipe de Puerto Plata'],

  // ── Costa Rica ──
  'San José': ['San Jose', 'San José'],
  'San Sebastián': ['San Sebastian', 'San José'],
  Coronado: ['Coronado', 'Vazquez de Coronado'],
  Tibás: ['Tibas', 'Tibás'],
  Moravia: ['Moravia', 'San Vicente de Moravia'],
  Sabanilla: ['Sabanilla', 'Montes de Oca'],
  'San Pedro': ['San Pedro', 'Montes de Oca'],
  Curridabat: ['Curridabat'],
  Desamparados: ['Desamparados'],
  Guadalupe: ['Guadalupe', 'Goicoechea'],
  'Santa Ana': ['Santa Ana', 'Lindora'],
  Alajuela: ['Alajuela'],
  'San Carlos': ['San Carlos', 'Ciudad Quesada'],
  'San Ramón': ['San Ramon', 'San Ramón'],
  Grecia: ['Grecia'],
  Cartago: ['Cartago'],
  Paraíso: ['Paraiso', 'Paraíso'],
  'Tres Ríos': ['Tres Rios', 'Tres Ríos', 'La Unión'],
  'La Unión': ['La Union', 'La Unión'],
  'El Guarco': ['El Guarco', 'Tejar'],
  Heredia: ['Heredia'],
  'San Joaquín de Flores': ['San Joaquin de Flores', 'Flores'],
  Liberia: ['Liberia'],
  Abangares: ['Abangares', 'Las Juntas'],
  Puntarenas: ['Puntarenas'],
  Jacó: ['Jaco', 'Jacó', 'Garabito'],
  Limón: ['Limon', 'Limón'],
  Guápiles: ['Guapiles', 'Guápiles', 'Pococi'],
  'Pérez Zeledón': ['Perez Zeledon', 'Pérez Zeledón', 'San Isidro de El General'],
};

interface StoreSeedData {
  nombre: string;
  codigo: string;
  direccion: string;
  ciudad: string;
  email: string;
  telefono: string;
  zona: string;
  latitud: number;
  longitud: number;
  region: string;
  location_type: string;
  store_format: string;
  seating_capacity: number;
  sales_tier: string;
  has_drive_thru: boolean;
  has_delivery: boolean;
  operating_hours: Record<string, { open: string; close: string }>;
  opening_date: string;
  manager_name: string;
  tags: string[];
  activo: boolean;
  metadata: Record<string, any>;
}

const STORE_DEFINITIONS: StoreSeedData[] = [
  // ── Santo Domingo (10 tiendas) ──────────────────────────────
  {
    nombre: 'Taco Bell - Máximo Gómez',
    codigo: 'TB-SD-001',
    direccion: 'Av. Máximo Gómez #100, esq. Av. 27 de Febrero',
    ciudad: 'Santo Domingo',
    email: 'tb.maximo.gomez@tacobell.com.do',
    telefono: '+1-809-555-1001',
    zona: 'Ensanche La Paz',
    latitud: 18.4752,
    longitud: -69.9178,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 65,
    sales_tier: 'A',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2018-03-10',
    manager_name: 'Carlos Rodríguez',
    tags: ['drive-thru', 'wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-001' },
  },
  {
    nombre: 'Taco Bell - Lope de Vega',
    codigo: 'TB-SD-002',
    direccion: 'Av. Lope de Vega #13, esq. Av. México',
    ciudad: 'Santo Domingo',
    email: 'tb.lope.de.vega@tacobell.com.do',
    telefono: '+1-809-555-1002',
    zona: 'Gazcue',
    latitud: 18.4621,
    longitud: -69.9123,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    opening_date: '2015-11-20',
    manager_name: 'Ana María Fermín',
    tags: ['wifi', 'estacionamiento'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-002' },
  },
  {
    nombre: 'Taco Bell - Núñez de Cáceres',
    codigo: 'TB-SD-003',
    direccion: 'Av. Núñez de Cáceres esq. Av. Rómulo Betancourt',
    ciudad: 'Santo Domingo',
    email: 'tb.nunez.caceres@tacobell.com.do',
    telefono: '+1-809-555-1003',
    zona: 'Bella Vista',
    latitud: 18.4567,
    longitud: -69.9354,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 70,
    sales_tier: 'A',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2019-07-22',
    manager_name: 'Pedro Suárez',
    tags: ['drive-thru', 'wifi', 'remodelado'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-003' },
  },
  {
    nombre: 'Taco Bell - Winston Churchill',
    codigo: 'TB-SD-004',
    direccion: 'Av. Winston Churchill esq. Gustavo Mejía Ricart',
    ciudad: 'Santo Domingo',
    email: 'tb.winston.churchill@tacobell.com.do',
    telefono: '+1-809-555-1004',
    zona: 'Piantini',
    latitud: 18.4702,
    longitud: -69.9448,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 80,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2016-05-18',
    manager_name: 'Laura Jiménez',
    tags: ['wifi', 'terraza', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-004' },
  },
  {
    nombre: 'Taco Bell - Sarasota',
    codigo: 'TB-SD-005',
    direccion: 'Av. Sarasota esq. Arrayanes',
    ciudad: 'Santo Domingo',
    email: 'tb.sarasota@tacobell.com.do',
    telefono: '+1-809-555-1005',
    zona: 'Bella Vista',
    latitud: 18.4509,
    longitud: -69.9287,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 60,
    sales_tier: 'B',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '23:30' },
      saturday: { open: '09:00', close: '23:30' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2017-10-05',
    manager_name: 'Roberto Díaz',
    tags: ['drive-thru', 'wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-005' },
  },
  {
    nombre: 'Taco Bell - Galería 360',
    codigo: 'TB-SD-006',
    direccion: 'Av. John F. Kennedy, Galería 360, Local F-12',
    ciudad: 'Santo Domingo',
    email: 'tb.galeria360@tacobell.com.do',
    telefono: '+1-809-555-1006',
    zona: 'La Julia',
    latitud: 18.4815,
    longitud: -69.9321,
    region: 'Metropolitana',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 45,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    opening_date: '2022-04-15',
    manager_name: 'Carolina Mota',
    tags: ['mall', 'nuevo'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-006' },
  },
  {
    nombre: 'Taco Bell - Blue Mall',
    codigo: 'TB-SD-007',
    direccion: 'Av. Winston Churchill, Blue Mall, Local 2B',
    ciudad: 'Santo Domingo',
    email: 'tb.bluemall@tacobell.com.do',
    telefono: '+1-809-555-1007',
    zona: 'Piantini',
    latitud: 18.4739,
    longitud: -69.9456,
    region: 'Metropolitana',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    opening_date: '2022-10-10',
    manager_name: 'Fernando Castro',
    tags: ['mall', 'wifi', 'exclusivo'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-017' },
  },
  {
    nombre: 'Taco Bell - Acrópolis Center',
    codigo: 'TB-SD-008',
    direccion: 'Av. Winston Churchill, Acrópolis Center, Local F-15',
    ciudad: 'Santo Domingo',
    email: 'tb.acropolis@tacobell.com.do',
    telefono: '+1-809-555-1008',
    zona: 'Serallés',
    latitud: 18.4682,
    longitud: -69.9423,
    region: 'Metropolitana',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    opening_date: '2020-08-15',
    manager_name: 'Patricia Jiménez',
    tags: ['mall', 'wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-018' },
  },
  {
    nombre: 'Taco Bell - Megacentro',
    codigo: 'TB-SD-009',
    direccion: 'Av. San Vicente de Paúl, Megacentro, Local F-22',
    ciudad: 'Santo Domingo',
    email: 'tb.megacentro@tacobell.com.do',
    telefono: '+1-809-555-1009',
    zona: 'Los Mina',
    latitud: 18.4928,
    longitud: -69.8859,
    region: 'Metropolitana',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '21:00' },
      tuesday: { open: '10:00', close: '21:00' },
      wednesday: { open: '10:00', close: '21:00' },
      thursday: { open: '10:00', close: '21:00' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '20:00' },
    },
    opening_date: '2017-06-20',
    manager_name: 'Ricardo Sánchez',
    tags: ['mall', 'wifi', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-019' },
  },
  {
    nombre: 'Taco Bell - Downtown Center',
    codigo: 'TB-SD-010',
    direccion: 'Av. Núñez de Cáceres esq. Av. Winston Churchill',
    ciudad: 'Santo Domingo',
    email: 'tb.downtowncenter@tacobell.com.do',
    telefono: '+1-809-555-1010',
    zona: 'Piantini',
    latitud: 18.4715,
    longitud: -69.9412,
    region: 'Metropolitana',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 75,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2023-12-01',
    manager_name: 'Sofía Peña',
    tags: ['nuevo', 'remodelado', 'wifi', 'terraza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-020' },
  },

  // ── Santiago (2 tiendas) ──────────────────────────────
  {
    nombre: 'Taco Bell - Santiago Centro',
    codigo: 'TB-ST-001',
    direccion: 'Av. 27 de Febrero #105, esquina Av. Estrella Sadhalá',
    ciudad: 'Santiago',
    email: 'tb.santiago.centro@tacobell.com.do',
    telefono: '+1-809-555-2001',
    zona: 'Centro',
    latitud: 19.4567,
    longitud: -70.7056,
    region: 'Norte',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 75,
    sales_tier: 'A',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '23:00' },
      thursday: { open: '08:00', close: '23:00' },
      friday: { open: '08:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '22:00' },
    },
    opening_date: '2014-02-28',
    manager_name: 'José Ramírez',
    tags: ['drive-thru', 'wifi', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-007' },
  },
  {
    nombre: 'Taco Bell - Santiago Norte',
    codigo: 'TB-ST-002',
    direccion: 'Av. Circunvalación Norte, Plaza La Sirena',
    ciudad: 'Santiago',
    email: 'tb.santiago.norte@tacobell.com.do',
    telefono: '+1-809-555-2002',
    zona: 'Reparto Universitario',
    latitud: 19.4763,
    longitud: -70.7152,
    region: 'Norte',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 60,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    opening_date: '2020-09-12',
    manager_name: 'Marta Santana',
    tags: ['wifi', 'nuevo'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-008' },
  },

  // ── Punta Cana / Bávaro (2 tiendas) ──────────────────
  {
    nombre: 'Taco Bell - Punta Cana Downtown',
    codigo: 'TB-PC-001',
    direccion: 'Downtown Punta Cana, Local 7A, Blvd. El Dorado',
    ciudad: 'Punta Cana',
    email: 'tb.puntacana.downtown@tacobell.com.do',
    telefono: '+1-809-555-3001',
    zona: 'El Dorado',
    latitud: 18.5712,
    longitud: -68.4153,
    region: 'Este',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 90,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '23:00' },
      tuesday: { open: '10:00', close: '23:00' },
      wednesday: { open: '10:00', close: '23:00' },
      thursday: { open: '10:00', close: '23:00' },
      friday: { open: '10:00', close: '00:00' },
      saturday: { open: '10:00', close: '00:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    opening_date: '2023-02-10',
    manager_name: 'Luis Pérez',
    tags: ['nuevo', 'turístico', 'wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-009' },
  },
  {
    nombre: 'Taco Bell - Bávaro',
    codigo: 'TB-PC-002',
    direccion: 'Plaza San Juan, Av. Barceló, Bávaro',
    ciudad: 'Punta Cana',
    email: 'tb.bavaro@tacobell.com.do',
    telefono: '+1-809-555-3002',
    zona: 'Bávaro',
    latitud: 18.6534,
    longitud: -68.4521,
    region: 'Este',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 70,
    sales_tier: 'A',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '23:00' },
      tuesday: { open: '09:00', close: '23:00' },
      wednesday: { open: '09:00', close: '23:00' },
      thursday: { open: '09:00', close: '23:00' },
      friday: { open: '09:00', close: '00:00' },
      saturday: { open: '09:00', close: '00:00' },
      sunday: { open: '10:00', close: '23:00' },
    },
    opening_date: '2023-08-25',
    manager_name: 'María Reyes',
    tags: ['nuevo', 'drive-thru', 'playa'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-010' },
  },

  // ── La Romana (1 tienda) ──────────────────────────────
  {
    nombre: 'Taco Bell - La Romana',
    codigo: 'TB-LR-001',
    direccion: 'Av. Santa Rosa esq. Libertad, Plaza Romana',
    ciudad: 'La Romana',
    email: 'tb.laromana@tacobell.com.do',
    telefono: '+1-809-555-4001',
    zona: 'Santa Rosa',
    latitud: 18.4289,
    longitud: -68.9783,
    region: 'Este',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    opening_date: '2021-11-18',
    manager_name: 'Rafael Cedeño',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-011' },
  },

  // ── Higüey (1 tienda) ────────────────────────────────
  {
    nombre: 'Taco Bell - Higüey',
    codigo: 'TB-LR-002',
    direccion: 'Av. Altagracia #45, esq. Sánchez',
    ciudad: 'Higüey',
    email: 'tb.higuey@tacobell.com.do',
    telefono: '+1-809-555-4002',
    zona: 'Centro',
    latitud: 18.6189,
    longitud: -68.7178,
    region: 'Este',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'C',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    opening_date: '2022-06-30',
    manager_name: 'Diana Guerrero',
    tags: ['drive-thru', 'provincia'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-012' },
  },

  // ── San Cristóbal (1 tienda) ──────────────────────────
  {
    nombre: 'Taco Bell - San Cristóbal',
    codigo: 'TB-SC-001',
    direccion: 'Av. Constitución #50, Plaza Constitución',
    ciudad: 'San Cristóbal',
    email: 'tb.sancristobal@tacobell.com.do',
    telefono: '+1-809-555-5001',
    zona: 'Centro',
    latitud: 18.4176,
    longitud: -70.1089,
    region: 'Sur',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    opening_date: '2019-05-17',
    manager_name: 'Jorge Familia',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-013' },
  },

  // ── San Francisco de Macorís (1 tienda) ───────────────
  {
    nombre: 'Taco Bell - San Francisco',
    codigo: 'TB-SFM-001',
    direccion: 'Av. Libertad #121, esq. Sánchez',
    ciudad: 'San Francisco de Macorís',
    email: 'tb.sanfrancisco@tacobell.com.do',
    telefono: '+1-809-555-6001',
    zona: 'Centro',
    latitud: 19.3023,
    longitud: -70.2546,
    region: 'Norte',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 60,
    sales_tier: 'B',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    opening_date: '2021-03-22',
    manager_name: 'Rosa Hernández',
    tags: ['drive-thru', 'nuevo'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-014' },
  },

  // ── La Vega (1 tienda) ────────────────────────────────
  {
    nombre: 'Taco Bell - La Vega',
    codigo: 'TB-LV-001',
    direccion: 'Av. Pedro A. Lluberes #44, Plaza El Paseo',
    ciudad: 'La Vega',
    email: 'tb.lavega@tacobell.com.do',
    telefono: '+1-809-555-7001',
    zona: 'Centro',
    latitud: 19.2221,
    longitud: -70.5328,
    region: 'Norte',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'C',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '22:30' },
      saturday: { open: '09:00', close: '22:30' },
      sunday: { open: '10:00', close: '20:00' },
    },
    opening_date: '2020-02-14',
    manager_name: 'Manuel Tavárez',
    tags: [],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-015' },
  },

  // ── Puerto Plata (1 tienda) ───────────────────────────
  {
    nombre: 'Taco Bell - Puerto Plata',
    codigo: 'TB-PP-001',
    direccion: 'Malecón de Puerto Plata #101, Plaza Turística',
    ciudad: 'Puerto Plata',
    email: 'tb.puertoplata@tacobell.com.do',
    telefono: '+1-809-555-8001',
    zona: 'Malecón',
    latitud: 19.8013,
    longitud: -70.6945,
    region: 'Norte',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 70,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: {
      monday: { open: '10:00', close: '22:00' },
      tuesday: { open: '10:00', close: '22:00' },
      wednesday: { open: '10:00', close: '22:00' },
      thursday: { open: '10:00', close: '22:00' },
      friday: { open: '10:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '11:00', close: '22:00' },
    },
    opening_date: '2018-12-01',
    manager_name: 'Carmen López',
    tags: ['vista al mar', 'turístico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-016' },
  },
];

// ── Horarios reutilizables Costa Rica ───────────────────────────
const CR_STANDALONE_HOURS = {
  monday: { open: '09:00', close: '22:00' },
  tuesday: { open: '09:00', close: '22:00' },
  wednesday: { open: '09:00', close: '22:00' },
  thursday: { open: '09:00', close: '22:00' },
  friday: { open: '09:00', close: '23:00' },
  saturday: { open: '09:00', close: '23:00' },
  sunday: { open: '10:00', close: '21:00' },
};

const CR_MALL_HOURS = {
  monday: { open: '10:00', close: '21:00' },
  tuesday: { open: '10:00', close: '21:00' },
  wednesday: { open: '10:00', close: '21:00' },
  thursday: { open: '10:00', close: '21:00' },
  friday: { open: '10:00', close: '22:00' },
  saturday: { open: '10:00', close: '22:00' },
  sunday: { open: '11:00', close: '20:00' },
};

// ── Costa Rica (49 tiendas) ─────────────────────────────────────
const CR_STORE_DEFINITIONS: StoreSeedData[] = [
  // ── San José provincia (22 tiendas) ───────────────────────────
  {
    nombre: 'Taco Bell - Banco Central',
    codigo: 'TB-CR-001',
    direccion: 'Costado este del Banco Central, contiguo a AM/PM, San José',
    ciudad: 'San José',
    email: 'tb.bancocentral@tacobell.cr',
    telefono: '+506-2221-0001',
    zona: 'Centro',
    latitud: 9.933,
    longitud: -84.0779,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2016-03-15',
    manager_name: 'Carlos Ramírez',
    tags: ['wifi', 'centro'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-001' },
  },
  {
    nombre: 'Taco Bell - Merced',
    codigo: 'TB-CR-002',
    direccion: 'Costado norte de Parque La Merced, Avenida Segunda, San José',
    ciudad: 'San José',
    email: 'tb.merced@tacobell.cr',
    telefono: '+506-2221-0002',
    zona: 'Centro',
    latitud: 9.9366,
    longitud: -84.0825,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2015-08-20',
    manager_name: 'Ana Sofía Mora',
    tags: ['wifi', 'centro'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-002' },
  },
  {
    nombre: 'Taco Bell - Parque de La Paz',
    codigo: 'TB-CR-003',
    direccion: 'De la Rotonda Parque de la Paz 200 sureste, Centro Comercial a mano derecha',
    ciudad: 'San José',
    email: 'tb.parquedelapaz@tacobell.cr',
    telefono: '+506-2221-0003',
    zona: 'Hatillo',
    latitud: 9.9131,
    longitud: -84.0614,
    region: 'San José',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2019-05-10',
    manager_name: 'José Pablo Vargas',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-003' },
  },
  {
    nombre: 'Taco Bell - Teatro Nacional',
    codigo: 'TB-CR-004',
    direccion: 'Frente a la entrada de los museos del Banco Central, costado este de la Plaza de La Cultura',
    ciudad: 'San José',
    email: 'tb.teatronacional@tacobell.cr',
    telefono: '+506-2221-0004',
    zona: 'Centro',
    latitud: 9.9328,
    longitud: -84.0773,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2014-11-01',
    manager_name: 'María Fernanda Castro',
    tags: ['wifi', 'centro', 'turístico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-004' },
  },
  {
    nombre: 'Taco Bell - Torre Universal',
    codigo: 'TB-CR-005',
    direccion: 'Torre Universal Sabana, Sabana Sur, San José',
    ciudad: 'San José',
    email: 'tb.torreuniversal@tacobell.cr',
    telefono: '+506-2221-0005',
    zona: 'Sabana',
    latitud: 9.9315,
    longitud: -84.101,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2017-02-28',
    manager_name: 'Diego Hernández',
    tags: ['wifi', 'oficinas'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-005' },
  },
  {
    nombre: 'Taco Bell - Walmart San Sebastián',
    codigo: 'TB-CR-006',
    direccion: 'Food Court de Walmart de San Sebastián',
    ciudad: 'San Sebastián',
    email: 'tb.walmartss@tacobell.cr',
    telefono: '+506-2221-0006',
    zona: 'San Sebastián',
    latitud: 9.915,
    longitud: -84.095,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2018-09-12',
    manager_name: 'Gabriela Jiménez',
    tags: ['food-court', 'walmart'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-006' },
  },
  {
    nombre: 'Taco Bell - Coronado',
    codigo: 'TB-CR-007',
    direccion: 'Costado sur del parque de Coronado, San José',
    ciudad: 'Coronado',
    email: 'tb.coronado@tacobell.cr',
    telefono: '+506-2229-0007',
    zona: 'Centro',
    latitud: 9.9583,
    longitud: -84.0547,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2019-01-20',
    manager_name: 'Andrés Solano',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-007' },
  },
  {
    nombre: 'Taco Bell - Tibás',
    codigo: 'TB-CR-008',
    direccion: 'Tibás, de la estación de Bomberos, 200 metros oeste',
    ciudad: 'Tibás',
    email: 'tb.tibas@tacobell.cr',
    telefono: '+506-2235-0008',
    zona: 'Centro',
    latitud: 9.9554,
    longitud: -84.0781,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2017-07-15',
    manager_name: 'Laura Chaves',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-008' },
  },
  {
    nombre: 'Taco Bell - Moravia',
    codigo: 'TB-CR-009',
    direccion: 'Diagonal al Cementerio de Moravia (Los Colegios)',
    ciudad: 'Moravia',
    email: 'tb.moravia@tacobell.cr',
    telefono: '+506-2236-0009',
    zona: 'Los Colegios',
    latitud: 9.9572,
    longitud: -84.0567,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2016-10-05',
    manager_name: 'Alejandro Rojas',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-009' },
  },
  {
    nombre: 'Taco Bell - Plaza Lincoln',
    codigo: 'TB-CR-010',
    direccion: 'Mall Plaza Lincoln, Food Court, Moravia',
    ciudad: 'Moravia',
    email: 'tb.plazalincoln@tacobell.cr',
    telefono: '+506-2236-0010',
    zona: 'Lincoln',
    latitud: 9.958,
    longitud: -84.0483,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-03-18',
    manager_name: 'Valeria Alfaro',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-010' },
  },
  {
    nombre: 'Taco Bell - Cristo Sabanilla',
    codigo: 'TB-CR-011',
    direccion: 'Frente al Cristo de Sabanilla',
    ciudad: 'Sabanilla',
    email: 'tb.cristosabanilla@tacobell.cr',
    telefono: '+506-2224-0011',
    zona: 'Centro',
    latitud: 9.9367,
    longitud: -84.0442,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2018-04-22',
    manager_name: 'Daniel Ureña',
    tags: ['wifi', 'universitario'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-011' },
  },
  {
    nombre: 'Taco Bell - Mall San Pedro',
    codigo: 'TB-CR-012',
    direccion: 'Frente a Rotonda de la Hispanidad, San Pedro, Food Court',
    ciudad: 'San Pedro',
    email: 'tb.mallsanpedro@tacobell.cr',
    telefono: '+506-2225-0012',
    zona: 'Centro',
    latitud: 9.9329,
    longitud: -84.0509,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2015-06-30',
    manager_name: 'Catalina Vindas',
    tags: ['food-court', 'mall', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-012' },
  },
  {
    nombre: 'Taco Bell - UCR',
    codigo: 'TB-CR-013',
    direccion: 'Frente a la rectoría de la Universidad de Costa Rica, San Pedro',
    ciudad: 'San Pedro',
    email: 'tb.ucr@tacobell.cr',
    telefono: '+506-2225-0013',
    zona: 'UCR',
    latitud: 9.9372,
    longitud: -84.0524,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2014-03-10',
    manager_name: 'Luis Fernando Monge',
    tags: ['wifi', 'universitario', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-013' },
  },
  {
    nombre: 'Taco Bell - Granadilla',
    codigo: 'TB-CR-014',
    direccion: 'Granadilla de Curridabat, Centro comercial Plaza del Barrio, detrás de Liceo Franco Costarricense',
    ciudad: 'Curridabat',
    email: 'tb.granadilla@tacobell.cr',
    telefono: '+506-2272-0014',
    zona: 'Granadilla',
    latitud: 9.919,
    longitud: -84.024,
    region: 'San José',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2019-11-05',
    manager_name: 'Natalia Araya',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-014' },
  },
  {
    nombre: 'Taco Bell - Multiplaza del Este',
    codigo: 'TB-CR-015',
    direccion: 'Curridabat, Centro Comercial Multiplaza, Food Court',
    ciudad: 'Curridabat',
    email: 'tb.multiplazaeste@tacobell.cr',
    telefono: '+506-2272-0015',
    zona: 'Multiplaza',
    latitud: 9.9174,
    longitud: -84.0334,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2016-12-01',
    manager_name: 'Roberto Cascante',
    tags: ['food-court', 'mall', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-015' },
  },
  {
    nombre: 'Taco Bell - Triángulo',
    codigo: 'TB-CR-016',
    direccion: 'Curridabat 50 metros al oeste de la antigua Casa de José Figueres, contiguo a AM/PM',
    ciudad: 'Curridabat',
    email: 'tb.triangulo@tacobell.cr',
    telefono: '+506-2272-0016',
    zona: 'Centro',
    latitud: 9.921,
    longitud: -84.037,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2017-05-20',
    manager_name: 'Daniela Sánchez',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-016' },
  },
  {
    nombre: 'Taco Bell - Multicentro Desamparados',
    codigo: 'TB-CR-017',
    direccion: 'Multicentro Desamparados Food Court',
    ciudad: 'Desamparados',
    email: 'tb.multicentrodes@tacobell.cr',
    telefono: '+506-2250-0017',
    zona: 'Centro',
    latitud: 9.8984,
    longitud: -84.0629,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2018-08-15',
    manager_name: 'Marco Chinchilla',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-017' },
  },
  {
    nombre: 'Taco Bell - Plaza Expresso',
    codigo: 'TB-CR-018',
    direccion: 'Centro Comercial Expreso Desamparados, Carretera a San Rafael Arriba de Desamparados',
    ciudad: 'Desamparados',
    email: 'tb.plazaexpresso@tacobell.cr',
    telefono: '+506-2250-0018',
    zona: 'San Rafael Arriba',
    latitud: 9.8919,
    longitud: -84.0611,
    region: 'San José',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-01-10',
    manager_name: 'Stephanie Cordero',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-018' },
  },
  {
    nombre: 'Taco Bell - San Miguel',
    codigo: 'TB-CR-019',
    direccion: 'San Miguel de Desamparados, frente al Depósito Las Gravilias',
    ciudad: 'Desamparados',
    email: 'tb.sanmiguel@tacobell.cr',
    telefono: '+506-2250-0019',
    zona: 'San Miguel',
    latitud: 9.884,
    longitud: -84.067,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2021-06-15',
    manager_name: 'Fabián Quesada',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-019' },
  },
  {
    nombre: 'Taco Bell - Zona Centro',
    codigo: 'TB-CR-020',
    direccion: 'Centro comercial Zona Centro, San Rafael Abajo de Desamparados, 1.5 km al sur de Walmart San Sebastián',
    ciudad: 'Desamparados',
    email: 'tb.zonacentro@tacobell.cr',
    telefono: '+506-2250-0020',
    zona: 'San Rafael Abajo',
    latitud: 9.89,
    longitud: -84.066,
    region: 'San José',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2022-03-20',
    manager_name: 'Melissa Aguilar',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-020' },
  },
  {
    nombre: 'Taco Bell - Guadalupe',
    codigo: 'TB-CR-021',
    direccion: 'Centro comercial City Plaza, Cruce de Guadalupe Moravia',
    ciudad: 'Guadalupe',
    email: 'tb.guadalupe@tacobell.cr',
    telefono: '+506-2283-0021',
    zona: 'Centro',
    latitud: 9.9477,
    longitud: -84.0569,
    region: 'San José',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-09-01',
    manager_name: 'Esteban Brenes',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-021' },
  },
  {
    nombre: 'Taco Bell - Vistana del Este',
    codigo: 'TB-CR-022',
    direccion: 'Lindora, Del Lagar 100 m al norte, Santa Ana',
    ciudad: 'Santa Ana',
    email: 'tb.vistanaeste@tacobell.cr',
    telefono: '+506-2282-0022',
    zona: 'Lindora',
    latitud: 9.958,
    longitud: -84.178,
    region: 'San José',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2021-02-14',
    manager_name: 'Katherine Arguedas',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-022' },
  },

  // ── Alajuela provincia (8 tiendas) ────────────────────────────
  {
    nombre: 'Taco Bell - Alajuela Centro',
    codigo: 'TB-CR-023',
    direccion: 'Costado Sur de la Catedral de Alajuela',
    ciudad: 'Alajuela',
    email: 'tb.alajuelacentro@tacobell.cr',
    telefono: '+506-2441-0023',
    zona: 'Centro',
    latitud: 10.0162,
    longitud: -84.2116,
    region: 'Alajuela',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2015-01-20',
    manager_name: 'Óscar Villalobos',
    tags: ['wifi', 'centro'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-023' },
  },
  {
    nombre: 'Taco Bell - La Trinidad de Alajuela',
    codigo: 'TB-CR-024',
    direccion: 'La Trinidad Alajuela, Plaza Trinidad',
    ciudad: 'Alajuela',
    email: 'tb.latrinidad@tacobell.cr',
    telefono: '+506-2441-0024',
    zona: 'La Trinidad',
    latitud: 10.004,
    longitud: -84.21,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2019-08-12',
    manager_name: 'Cristina Esquivel',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-024' },
  },
  {
    nombre: 'Taco Bell - Plaza Real Alajuela',
    codigo: 'TB-CR-025',
    direccion: 'Centro comercial Plaza Real Alajuela, 200 metros al este de la bomba La Tropicana',
    ciudad: 'Alajuela',
    email: 'tb.plazareal@tacobell.cr',
    telefono: '+506-2441-0025',
    zona: 'Centro',
    latitud: 10.013,
    longitud: -84.207,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-06-15',
    manager_name: 'Mauricio Calvo',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-025' },
  },
  {
    nombre: 'Taco Bell - San Rafael de Alajuela',
    codigo: 'TB-CR-026',
    direccion: 'Centro Comercial Piedras Blancas, frente al Banco Nacional de San Rafael de Alajuela',
    ciudad: 'Alajuela',
    email: 'tb.sanrafaelalaj@tacobell.cr',
    telefono: '+506-2441-0026',
    zona: 'San Rafael',
    latitud: 10.019,
    longitud: -84.18,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2021-04-08',
    manager_name: 'Andrea Herrera',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-026' },
  },
  {
    nombre: 'Taco Bell - Tropicana Alajuela',
    codigo: 'TB-CR-027',
    direccion: 'Frente a la Bomba La Tropicana, Calle Ancha Alajuela',
    ciudad: 'Alajuela',
    email: 'tb.tropicana@tacobell.cr',
    telefono: '+506-2441-0027',
    zona: 'Calle Ancha',
    latitud: 10.017,
    longitud: -84.205,
    region: 'Alajuela',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2016-09-30',
    manager_name: 'Francisco Madrigal',
    tags: ['wifi', 'drive-thru'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-027' },
  },
  {
    nombre: 'Taco Bell - San Carlos',
    codigo: 'TB-CR-028',
    direccion: 'Ciudad Quesada, Plaza el Encuentro, área de comida',
    ciudad: 'San Carlos',
    email: 'tb.sancarlos@tacobell.cr',
    telefono: '+506-2460-0028',
    zona: 'Centro',
    latitud: 10.3254,
    longitud: -84.4271,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2022-01-20',
    manager_name: 'Tatiana Porras',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-028' },
  },
  {
    nombre: 'Taco Bell - San Ramón',
    codigo: 'TB-CR-029',
    direccion: 'Mall del Occidente, Food Court, San Ramón',
    ciudad: 'San Ramón',
    email: 'tb.sanramon@tacobell.cr',
    telefono: '+506-2445-0029',
    zona: 'Centro',
    latitud: 10.0875,
    longitud: -84.4704,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'C',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2021-11-10',
    manager_name: 'Alonso Camacho',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-029' },
  },
  {
    nombre: 'Taco Bell - Grecia',
    codigo: 'TB-CR-030',
    direccion: 'Mall Plaza Ingenio, Carretera a Sarchí, Food Court',
    ciudad: 'Grecia',
    email: 'tb.grecia@tacobell.cr',
    telefono: '+506-2494-0030',
    zona: 'Centro',
    latitud: 10.0724,
    longitud: -84.3127,
    region: 'Alajuela',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'C',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2022-07-05',
    manager_name: 'Sofía Valverde',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-030' },
  },

  // ── Cartago provincia (7 tiendas) ─────────────────────────────
  {
    nombre: 'Taco Bell - Cartago Ruinas',
    codigo: 'TB-CR-031',
    direccion: 'Frente a la Municipalidad de Cartago, Diagonal a las Ruinas',
    ciudad: 'Cartago',
    email: 'tb.cartagoruinas@tacobell.cr',
    telefono: '+506-2551-0031',
    zona: 'Centro',
    latitud: 9.8636,
    longitud: -83.9193,
    region: 'Cartago',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2015-04-18',
    manager_name: 'Jonathan Molina',
    tags: ['wifi', 'centro'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-031' },
  },
  {
    nombre: 'Taco Bell - Cartago San Luis',
    codigo: 'TB-CR-032',
    direccion: 'Esquina Noreste del Colegio San Luis Gonzaga, Cartago',
    ciudad: 'Cartago',
    email: 'tb.cartagosanluis@tacobell.cr',
    telefono: '+506-2551-0032',
    zona: 'San Luis',
    latitud: 9.857,
    longitud: -83.923,
    region: 'Cartago',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2017-09-22',
    manager_name: 'Paola Ledezma',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-032' },
  },
  {
    nombre: 'Taco Bell - Metrópoli Mall',
    codigo: 'TB-CR-033',
    direccion: 'Paseo Metrópoli, Cartago',
    ciudad: 'Cartago',
    email: 'tb.metropoli@tacobell.cr',
    telefono: '+506-2551-0033',
    zona: 'Metrópoli',
    latitud: 9.858,
    longitud: -83.935,
    region: 'Cartago',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2018-11-30',
    manager_name: 'Iván Barrantes',
    tags: ['wifi', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-033' },
  },
  {
    nombre: 'Taco Bell - Paraíso',
    codigo: 'TB-CR-034',
    direccion: 'Centro Comercial Plaza Paraíso Cartago, Entrada Principal a Campo Ayala',
    ciudad: 'Paraíso',
    email: 'tb.paraiso@tacobell.cr',
    telefono: '+506-2574-0034',
    zona: 'Centro',
    latitud: 9.8389,
    longitud: -83.8619,
    region: 'Cartago',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'C',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2021-08-14',
    manager_name: 'Yessenia Campos',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-034' },
  },
  {
    nombre: 'Taco Bell - Terramall',
    codigo: 'TB-CR-035',
    direccion: 'Centro Comercial Terramall, Tres Ríos',
    ciudad: 'Tres Ríos',
    email: 'tb.terramall@tacobell.cr',
    telefono: '+506-2279-0035',
    zona: 'Terramall',
    latitud: 9.905,
    longitud: -83.985,
    region: 'Cartago',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2016-05-20',
    manager_name: 'Bryan Elizondo',
    tags: ['wifi', 'mall', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-035' },
  },
  {
    nombre: 'Taco Bell - Villas de Ayarco',
    codigo: 'TB-CR-036',
    direccion: 'Villas de Ayarco, en San Juan de La Unión',
    ciudad: 'La Unión',
    email: 'tb.villasayarco@tacobell.cr',
    telefono: '+506-2279-0036',
    zona: 'San Juan',
    latitud: 9.906,
    longitud: -83.993,
    region: 'Cartago',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2020-04-15',
    manager_name: 'Adriana Fonseca',
    tags: ['wifi'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-036' },
  },
  {
    nombre: 'Taco Bell - El Guarco',
    codigo: 'TB-CR-037',
    direccion: '50 metros al norte del Restaurante El Quijongo, sobre carretera interamericana',
    ciudad: 'El Guarco',
    email: 'tb.elguarco@tacobell.cr',
    telefono: '+506-2551-0037',
    zona: 'Interamericana',
    latitud: 9.824,
    longitud: -83.9493,
    region: 'Cartago',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'C',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2022-10-01',
    manager_name: 'Kevin Trejos',
    tags: ['wifi', 'drive-thru', 'carretera'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-037' },
  },

  // ── Heredia provincia (5 tiendas) ─────────────────────────────
  {
    nombre: 'Taco Bell - Heredia Mercado Central',
    codigo: 'TB-CR-038',
    direccion: 'Esquina Noreste del Mercado central de Heredia',
    ciudad: 'Heredia',
    email: 'tb.herediamercado@tacobell.cr',
    telefono: '+506-2261-0038',
    zona: 'Centro',
    latitud: 10.0027,
    longitud: -84.1168,
    region: 'Heredia',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2015-10-12',
    manager_name: 'Carolina Ulloa',
    tags: ['wifi', 'centro'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-038' },
  },
  {
    nombre: 'Taco Bell - Paseo de las Flores',
    codigo: 'TB-CR-039',
    direccion: 'Frente a Universidad Latina de Heredia, Food Court',
    ciudad: 'Heredia',
    email: 'tb.paseoflores@tacobell.cr',
    telefono: '+506-2261-0039',
    zona: 'Paseo de las Flores',
    latitud: 10.005,
    longitud: -84.112,
    region: 'Heredia',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 45,
    sales_tier: 'A',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2016-08-18',
    manager_name: 'Manuel Salas',
    tags: ['food-court', 'mall', 'alto tráfico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-039' },
  },
  {
    nombre: 'Taco Bell - San Francisco de Heredia',
    codigo: 'TB-CR-040',
    direccion: 'San Francisco de Heredia, Centro Comercial Multiflores',
    ciudad: 'Heredia',
    email: 'tb.sanfranciscoh@tacobell.cr',
    telefono: '+506-2261-0040',
    zona: 'San Francisco',
    latitud: 9.989,
    longitud: -84.13,
    region: 'Heredia',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2019-12-05',
    manager_name: 'Pamela Gamboa',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-040' },
  },
  {
    nombre: 'Taco Bell - UNA',
    codigo: 'TB-CR-041',
    direccion: '100 m al sur de la entrada principal de la UNA, Heredia',
    ciudad: 'Heredia',
    email: 'tb.una@tacobell.cr',
    telefono: '+506-2261-0041',
    zona: 'UNA',
    latitud: 10.006,
    longitud: -84.113,
    region: 'Heredia',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2017-03-25',
    manager_name: 'René Badilla',
    tags: ['wifi', 'universitario'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-041' },
  },
  {
    nombre: 'Taco Bell - Vizcaya',
    codigo: 'TB-CR-042',
    direccion: 'Centro Comercial Plaza Vizcaya, 300 m al norte de la Escuela Estados Unidos, San Joaquín de Flores',
    ciudad: 'San Joaquín de Flores',
    email: 'tb.vizcaya@tacobell.cr',
    telefono: '+506-2265-0042',
    zona: 'Centro',
    latitud: 10.012,
    longitud: -84.144,
    region: 'Heredia',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-11-20',
    manager_name: 'Vivian Zamora',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-042' },
  },

  // ── Guanacaste provincia (2 tiendas) ──────────────────────────
  {
    nombre: 'Taco Bell - Liberia',
    codigo: 'TB-CR-043',
    direccion: 'Contiguo Hotel Boyeros, entrada principal de Liberia, Guanacaste',
    ciudad: 'Liberia',
    email: 'tb.liberia@tacobell.cr',
    telefono: '+506-2666-0043',
    zona: 'Centro',
    latitud: 10.6342,
    longitud: -85.4385,
    region: 'Guanacaste',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 55,
    sales_tier: 'B',
    has_drive_thru: true,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2018-06-10',
    manager_name: 'Fernando Gutiérrez',
    tags: ['wifi', 'drive-thru', 'turístico'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-043' },
  },
  {
    nombre: 'Taco Bell - Limonal',
    codigo: 'TB-CR-044',
    direccion: 'Cruce hacia el puente la Amistad, Limonal de Abangares, Guanacaste',
    ciudad: 'Abangares',
    email: 'tb.limonal@tacobell.cr',
    telefono: '+506-2662-0044',
    zona: 'Limonal',
    latitud: 10.205,
    longitud: -85.028,
    region: 'Guanacaste',
    location_type: 'standalone',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'C',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_STANDALONE_HOURS },
    opening_date: '2021-09-15',
    manager_name: 'Marcela Bolaños',
    tags: ['wifi', 'carretera'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-044' },
  },

  // ── Puntarenas provincia (2 tiendas) ──────────────────────────
  {
    nombre: 'Taco Bell - Puntarenas',
    codigo: 'TB-CR-045',
    direccion: 'Centro Comercial Plaza Puerto 23, Roble de Puntarenas',
    ciudad: 'Puntarenas',
    email: 'tb.puntarenas@tacobell.cr',
    telefono: '+506-2661-0045',
    zona: 'Roble',
    latitud: 9.9779,
    longitud: -84.8388,
    region: 'Puntarenas',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2019-03-08',
    manager_name: 'Ricardo Segura',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-045' },
  },
  {
    nombre: 'Taco Bell - Jacó',
    codigo: 'TB-CR-046',
    direccion: 'Centro Comercial Plaza Jacó, Frente al hotel Best Western',
    ciudad: 'Jacó',
    email: 'tb.jaco@tacobell.cr',
    telefono: '+506-2643-0046',
    zona: 'Centro',
    latitud: 9.6131,
    longitud: -84.6296,
    region: 'Puntarenas',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2018-12-20',
    manager_name: 'Diana Acuña',
    tags: ['wifi', 'turístico', 'playa'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-046' },
  },

  // ── Limón provincia (2 tiendas) ───────────────────────────────
  {
    nombre: 'Taco Bell - Plaza Moín',
    codigo: 'TB-CR-047',
    direccion: 'Limón, carretera José Joaquín Trejos Fernández, en plaza Moín',
    ciudad: 'Limón',
    email: 'tb.plazamoin@tacobell.cr',
    telefono: '+506-2758-0047',
    zona: 'Moín',
    latitud: 9.9907,
    longitud: -83.0359,
    region: 'Limón',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 50,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2020-07-22',
    manager_name: 'Edgar Retana',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-047' },
  },
  {
    nombre: 'Taco Bell - Guápiles',
    codigo: 'TB-CR-048',
    direccion: 'Plaza Vistana, frente a la bomba Delta, Carretera Braulio Carrillo, Guápiles',
    ciudad: 'Guápiles',
    email: 'tb.guapiles@tacobell.cr',
    telefono: '+506-2710-0048',
    zona: 'Centro',
    latitud: 10.2146,
    longitud: -83.7876,
    region: 'Limón',
    location_type: 'mall',
    store_format: 'regular',
    seating_capacity: 45,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2021-05-30',
    manager_name: 'Marisol Delgado',
    tags: ['wifi', 'plaza'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-048' },
  },

  // ── Pérez Zeledón (1 tienda) ──────────────────────────────────
  {
    nombre: 'Taco Bell - Pérez Zeledón',
    codigo: 'TB-CR-049',
    direccion: 'Mall Monte General, Food Court, Pérez Zeledón',
    ciudad: 'Pérez Zeledón',
    email: 'tb.perezeledon@tacobell.cr',
    telefono: '+506-2771-0049',
    zona: 'Centro',
    latitud: 9.378,
    longitud: -83.701,
    region: 'San José',
    location_type: 'mall',
    store_format: 'kiosk',
    seating_capacity: 40,
    sales_tier: 'B',
    has_drive_thru: false,
    has_delivery: true,
    operating_hours: { ...CR_MALL_HOURS },
    opening_date: '2022-04-15',
    manager_name: 'Pablo Orozco',
    tags: ['food-court', 'mall'],
    activo: true,
    metadata: { pos_type: 'micros', integration_id: 'TB-CR-049' },
  },
];

/**
 * Normaliza un string para comparación (sin acentos, minúsculas)
 */
function normalize(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * Busca el geo_city_id correspondiente para una ciudad del store
 */
async function findGeoCityId(
  cityRepo: ReturnType<DataSource['getRepository']>,
  storeCiudad: string,
): Promise<string | null> {
  const lookupNames = CITY_LOOKUP[storeCiudad];
  if (!lookupNames) return null;

  for (const name of lookupNames) {
    // Buscar por nombre normalizado
    const city = await cityRepo
      .createQueryBuilder('city')
      .where('city.name_normalized = :normalized', {
        normalized: normalize(name),
      })
      .getOne();

    if (city) return city.id;

    // Buscar en aliases
    const cityByAlias = await cityRepo
      .createQueryBuilder('city')
      .where(':alias = ANY(city.aliases)', { alias: name })
      .getOne();

    if (cityByAlias) return cityByAlias.id;
  }

  return null;
}

/**
 * Procesa un lote de stores para una company específica
 */
async function seedStoresForCompany(
  storeRepo: ReturnType<DataSource['getRepository']>,
  cityRepo: ReturnType<DataSource['getRepository']>,
  companyId: string,
  storeDefs: StoreSeedData[],
  cityIdCache: Record<string, string | null>,
): Promise<{ created: number; updated: number }> {
  let created = 0;
  let updated = 0;

  for (const storeDef of storeDefs) {
    const existingStore = await storeRepo.findOne({
      where: { codigo: storeDef.codigo },
    });

    // Resolver geo_city_id (con cache)
    if (!(storeDef.ciudad in cityIdCache)) {
      cityIdCache[storeDef.ciudad] = await findGeoCityId(cityRepo, storeDef.ciudad);
    }
    const geoCityId = cityIdCache[storeDef.ciudad];

    const storePayload = {
      company_id: companyId,
      nombre: storeDef.nombre,
      codigo: storeDef.codigo,
      direccion: storeDef.direccion,
      ciudad: storeDef.ciudad,
      email: storeDef.email,
      telefono: storeDef.telefono,
      zona: storeDef.zona,
      latitud: storeDef.latitud,
      longitud: storeDef.longitud,
      region: storeDef.region,
      location_type: storeDef.location_type,
      store_format: storeDef.store_format,
      seating_capacity: storeDef.seating_capacity,
      sales_tier: storeDef.sales_tier,
      has_drive_thru: storeDef.has_drive_thru,
      has_delivery: storeDef.has_delivery,
      operating_hours: storeDef.operating_hours,
      opening_date: storeDef.opening_date,
      manager_name: storeDef.manager_name,
      tags: storeDef.tags,
      activo: storeDef.activo,
      metadata: storeDef.metadata,
      ...(geoCityId ? { geo_city_id: geoCityId } : {}),
    };

    if (existingStore) {
      await storeRepo.save(
        storeRepo.create({
          id: existingStore.id,
          ...storePayload,
        }),
      );
      updated++;
      const cityLabel = geoCityId ? 'OK geo' : 'WARN sin geo';
      console.log(`  [UPDATE] Store "${storeDef.codigo}" actualizada (${cityLabel})`);
      continue;
    }

    const store = storeRepo.create(storePayload);
    await storeRepo.save(store);
    created++;

    const cityLabel = geoCityId ? 'OK geo' : 'WARN sin geo';
    console.log(`  [CREATE] Store "${storeDef.codigo}" creada (${cityLabel})`);
  }

  return { created, updated };
}

/**
 * Seed de tiendas Taco Bell (RD + CR)
 *
 * Requiere que se hayan ejecutado previamente:
 * - seedGeography (para geo_city_id)
 * - seedCompanies (para company_id)
 */
export async function seedStores(dataSource: DataSource): Promise<void> {
  const storeRepo = dataSource.getRepository(StoreEntity);
  const companyRepo = dataSource.getRepository(CompanyEntity);
  const cityRepo = dataSource.getRepository(GeoCityEntity);

  console.log('\n┌────────────────────────────────────────────────────┐');
  console.log('│  🏪 SEEDING STORES (Taco Bell RD + CR)             │');
  console.log('└────────────────────────────────────────────────────┘');

  // Cache compartido de geo_city_ids
  const cityIdCache: Record<string, string | null> = {};
  let totalCreated = 0;
  let totalUpdated = 0;

  // ── República Dominicana ──
  const tacoBellRD = await companyRepo.findOne({
    where: { subdomain: 'republica' },
  });

  if (tacoBellRD) {
    console.log('\n  -- Taco Bell República Dominicana (20 tiendas) --');
    const rd = await seedStoresForCompany(storeRepo, cityRepo, tacoBellRD.id, STORE_DEFINITIONS, cityIdCache);
    totalCreated += rd.created;
    totalUpdated += rd.updated;
  } else {
    console.log('  ⚠ Company "Taco Bell Republica Dominicana" no encontrada. Saltando stores RD.');
  }

  // ── Costa Rica ──
  const tacoBellCR = await companyRepo.findOne({
    where: { subdomain: 'costarica' },
  });

  if (tacoBellCR) {
    console.log('\n  -- Taco Bell Costa Rica (49 tiendas) --');
    const cr = await seedStoresForCompany(storeRepo, cityRepo, tacoBellCR.id, CR_STORE_DEFINITIONS, cityIdCache);
    totalCreated += cr.created;
    totalUpdated += cr.updated;
  } else {
    console.log('  ⚠ Company "Taco Bell Costa Rica" no encontrada. Saltando stores CR.');
  }

  // Resumen
  const totalStores = await storeRepo.count();
  console.log('\n  📊 Resumen:');
  console.log(`     Creadas: ${totalCreated}`);
  console.log(`     Actualizadas: ${totalUpdated}`);
  console.log(`     Total en BD: ${totalStores}`);
  console.log('\n  ✅ Stores seeded successfully');
}


